import { z } from 'zod';

export const AddStoreSchema = z.object({
    Store_Code: z.string().min(1, 'store code is required'),
    Store_Type: z.string().optional(),
    Transaction_Type: z.string().optional(),
    Store_Name: z.string().min(1, 'store name is required'),
    Representative: z.string().optional(),
    Representative_ID: z.string().optional(),
    Phone_Number: z.string().optional(),
    Fax_Number: z.string().optional(),
    Email: z.string().optional(),
    Homepage: z.string().optional(),
    Total_Area: z.string().optional(),
    Store_Area: z.string().optional(),
    Parking_Space: z.string().optional(),
    Employee_Count: z.string().optional(),
    Bank_Name: z.string().optional(),
    Account_Number: z.string().optional(),
    Account_Holder: z.string().optional(),
    Transaction_Start_Date: z.string().optional(),
    Transaction_End_Date: z.string().optional(),
    Business_Number_1: z.string().optional(),
    Business_Number_2: z.string().optional(),
    Business_Number_3: z.string().optional(),
    Postal_Code: z.string().optional(),
    Address: z.string().optional(),
    Detailed_Address: z.string().optional(),
    Business_Type: z.string().optional(),
    Business_Category: z.string().optional(),
    Display_Order: z.string().optional(),
    Transaction_Level: z.string().optional(),
    Brand_ID: z.string().optional(),
    Brand_Name: z.string().optional(),
    Viettel_ID: z.string().optional(),
    Viettel_Password: z.string().optional(),
    Template_Code: z.string().optional(),
    Invoice_Series: z.string().optional(),
});
