import { z } from 'zod';

export const AddStoreSchema = z.object({
    Store_Code: z.string().min(1, 'store code is required').max(5, 'store code cannot exceed 5 characters'),
    Store_Type: z.string().max(10, 'store type cannot exceed 10 characters').optional(),
    Transaction_Type: z.string().max(10, 'transaction type cannot exceed 10 characters').optional(),
    Store_Name: z.string().min(1, 'store name is required'),
    Representative: z.string().optional(),
    Representative_ID: z.string().max(5, 'representative ID cannot exceed 5 characters').optional(),
    Phone_Number: z.string().optional(),
    Fax_Number: z.string().optional(),
    Email: z.string().optional(),
    Homepage: z.string().optional(),
    Total_Area: z.string().optional(),
    Store_Area: z.string().optional(),
    Parking_Space: z.string().optional(),
    Employee_Count: z.string().optional(),
    Bank_Name: z.string().optional(),
    Account_Number: z.string().optional(),
    Account_Holder: z.string().optional(),
    Transaction_Start_Date: z.string().optional(),
    Transaction_End_Date: z.string().optional(),
    Business_Number_1: z.string().max(3, 'Business Number 1 cannot exceed 3 characters').optional(),
    Business_Number_2: z.string().max(2, 'Business Number 2 cannot exceed 2 characters').optional(),
    Business_Number_3: z.string().max(10, 'Business Number 3 cannot exceed 10 characters').optional(),
    Postal_Code: z.string().max(10, 'Postal Code  cannot exceed 10 characters').optional(),
    Address: z.string().optional(),
    Detailed_Address: z.string().optional(),
    Business_Type: z.string().optional(),
    Business_Category: z.string().optional(),
    Display_Order: z.string().optional(),
    Transaction_Level: z.string().optional(),
    Brand_ID: z.string().optional(),
    Brand_Name: z.string().optional(),
    Viettel_ID: z.string().optional(),
    Viettel_Password: z.string().optional(),
    Template_Code: z.string().max(10, 'Template Code  cannot exceed 10 characters').optional(),
    Invoice_Series: z.string().max(10, 'Invoice Series  cannot exceed 10 characters').optional(),
});
