import GroupManagement from './GroupManagement';
import StoreInfo from './StoreInfo';
import StoreList from './StoreList';
import WarehouseManagement from './WarehouseManagement';
import CashDrawer from './CashDrawer';
import Discount from './Discount';
import EmployeeGroup from './EmployeeGroup';
import EmployeeInfo from './EmployeeInfo';
import EmployeeList from './EmployeeList';
import MenuSetup from './MenuSetup';
import ItemRecipeManagement from './ItemRecipeManagement';
import ItemRecipeManager from './ItemRecipeManager';
import ToppingSettings from './ToppingSettings';
import SubMenu from './SubMenu';
import MenuSearch from './MenuSearch';
import InventoryItemSearch from './InventoryItemSearch';
import MenuBoardManagement from './MenuBoardManagement';
import PosMenuBoard from './PosMenuBoard';
import CategoryManager from './CategoryManager';
import RecipeBuilder from './RecipeBuilder';
import RecipeSearch from './RecipeSearch';
import KitchenMemo from './KitchenMemo';
import ItemManagementByStrore from './ItemManagementByStrore';
import ChangeOfMultilingualName from './ChangeOfMultilingualName';
import ItemLinkedCodeManagement from './ItemLinkedCodeManagement';
import MainMenuSetting from './MainMenuSetting';
import TableLocationManager from './TableLocationManager';
import TableDesignSetting from './TableDesignSetting';
import POSFavoriteFunctionButton from './POSFavoriteFunctionButton';
import PaymentButtonSetting from './PaymentButtonSetting';
import KioskImageSettings from './KioskImageSettings';
import UPOrderImageSettings from './UPOrderImageSettings';
import KioskFunctionSetting from './KioskFunctionSetting';
export { default } from './BasicSettings';

export { GroupManagement, StoreInfo, StoreList, WarehouseManagement, CashDrawer, Discount, EmployeeGroup };
export { EmployeeInfo, EmployeeList, MenuSetup, ItemRecipeManagement, ItemRecipeManager, ToppingSettings };
export { SubMenu, MenuSearch, InventoryItemSearch, MenuBoardManagement, PosMenuBoard, CategoryManager };
export { RecipeBuilder, RecipeSearch, KitchenMemo, ItemManagementByStrore, ChangeOfMultilingualName };
export { ItemLinkedCodeManagement, MainMenuSetting, TableLocationManager, TableDesignSetting };
export { POSFavoriteFunctionButton, PaymentButtonSetting, KioskImageSettings, UPOrderImageSettings };
export { KioskFunctionSetting };
