export const storeListFake = [
    {
        key: '0',
        storeCode: '00001',
        storeType: 'Retail',
        transactionType: 'Cash',
        name: 'Cửa hàng A',
        representative: 'Nguyễn Văn A',
        representativeId: 'REP01',
        phoneNumber: '0123456789',
        faxNumber: '0987654321',
        email: 'exampleA@mail.com',
        homepage: 'http://storeA.com',
        totalArea: 150,
        storeArea: 100,
        parkingSpaces: 20,
        employeeCount: 5,
        bankName: 'Ngân hàng A',
        accountNumber: '123456789',
        accountHolder: 'Nguyễn Văn A',
        transactionStartDate: new Date('2023-01-01'),
        transactionEndDate: new Date('2024-01-01'),
        businessNumber1: '123',
        businessNumber2: '45',
        businessNumber3: '67890',
        postalCode: '100000',
        address: 'Địa chỉ A',
        detailedAddress: 'Chi tiết địa chỉ A',
        businessType: 'Bán lẻ',
        businessCategory: 'Thời trang',
        displayOrder: 1,
        transactionLevel: 1,
        brandId: 'BRAND01',
        brandName: 'Thương hiệu A',
        viettelId: 'ViettelA',
        viettelPassword: 'passwordA',
        templateCode: 'TEMP01',
        invoiceSeries: 'INV001',
    },
    {
        key: '1',
        storeCode: '00002',
        storeType: 'Wholesale',
        transactionType: 'Credit',
        name: 'Cửa hàng B',
        representative: 'Trần Văn B',
        representativeId: 'REP02',
        phoneNumber: '0123456788',
        faxNumber: '0987654320',
        email: 'exampleB@mail.com',
        homepage: 'http://storeB.com',
        totalArea: 200,
        storeArea: 150,
        parkingSpaces: 30,
        employeeCount: 10,
        bankName: 'Ngân hàng B',
        accountNumber: '987654321',
        accountHolder: 'Trần Văn B',
        transactionStartDate: new Date('2023-02-01'),
        transactionEndDate: new Date('2024-02-01'),
        businessNumber1: '987',
        businessNumber2: '65',
        businessNumber3: '43210',
        postalCode: '200000',
        address: 'Địa chỉ B',
        detailedAddress: 'Chi tiết địa chỉ B',
        businessType: 'Bán buôn',
        businessCategory: 'Điện máy',
        displayOrder: 2,
        transactionLevel: 2,
        brandId: 'BRAND02',
        brandName: 'Thương hiệu B',
        viettelId: 'ViettelB',
        viettelPassword: 'passwordB',
        templateCode: 'TEMP02',
        invoiceSeries: 'INV002',
    },
    {
        key: '2',
        storeCode: '00003',
        storeType: 'Franchise',
        transactionType: 'Cash',
        name: 'Cửa hàng C',
        representative: 'Lê Văn C',
        representativeId: 'REP03',
        phoneNumber: '0123456787',
        faxNumber: '0987654319',
        email: 'exampleC@mail.com',
        homepage: 'http://storeC.com',
        totalArea: 180,
        storeArea: 120,
        parkingSpaces: 25,
        employeeCount: 8,
        bankName: 'Ngân hàng C',
        accountNumber: '456789123',
        accountHolder: 'Lê Văn C',
        transactionStartDate: new Date('2023-03-01'),
        transactionEndDate: new Date('2024-03-01'),
        businessNumber1: '456',
        businessNumber2: '78',
        businessNumber3: '12345',
        postalCode: '300000',
        address: 'Địa chỉ C',
        detailedAddress: 'Chi tiết địa chỉ C',
        businessType: 'Nhượng quyền',
        businessCategory: 'Thực phẩm',
        displayOrder: 3,
        transactionLevel: 3,
        brandId: 'BRAND03',
        brandName: 'Thương hiệu C',
        viettelId: 'ViettelC',
        viettelPassword: 'passwordC',
        templateCode: 'TEMP03',
        invoiceSeries: 'INV003',
    },
    {
        key: '3',
        storeCode: '00004',
        storeType: 'Online',
        transactionType: 'Credit',
        name: 'Cửa hàng D',
        representative: 'Phạm Văn D',
        representativeId: 'REP04',
        phoneNumber: '0123456786',
        faxNumber: '0987654318',
        email: 'exampleD@mail.com',
        homepage: 'http://storeD.com',
        totalArea: 120,
        storeArea: 80,
        parkingSpaces: 15,
        employeeCount: 3,
        bankName: 'Ngân hàng D',
        accountNumber: '321654987',
        accountHolder: 'Phạm Văn D',
        transactionStartDate: new Date('2023-04-01'),
        transactionEndDate: new Date('2024-04-01'),
        businessNumber1: '321',
        businessNumber2: '65',
        businessNumber3: '98765',
        postalCode: '400000',
        address: 'Địa chỉ D',
        detailedAddress: 'Chi tiết địa chỉ D',
        businessType: 'Bán hàng trực tuyến',
        businessCategory: 'Sách',
        displayOrder: 4,
        transactionLevel: 1,
        brandId: 'BRAND04',
        brandName: 'Thương hiệu D',
        viettelId: 'ViettelD',
        viettelPassword: 'passwordD',
        templateCode: 'TEMP04',
        invoiceSeries: 'INV004',
    },
    {
        key: '4',
        storeCode: '00005',
        storeType: 'Retail',
        transactionType: 'Cash',
        name: 'Cửa hàng E',
        representative: 'Nguyễn Thị E',
        representativeId: 'REP05',
        phoneNumber: '0123456785',
        faxNumber: '0987654317',
        email: 'exampleE@mail.com',
        homepage: 'http://storeE.com',
        totalArea: 160,
        storeArea: 110,
        parkingSpaces: 22,
        employeeCount: 6,
        bankName: 'Ngân hàng E',
        accountNumber: '654789321',
        accountHolder: 'Nguyễn Thị E',
        transactionStartDate: new Date('2023-05-01'),
        transactionEndDate: new Date('2024-05-01'),
        businessNumber1: '654',
        businessNumber2: '32',
        businessNumber3: '54321',
        postalCode: '500000',
        address: 'Địa chỉ E',
        detailedAddress: 'Chi tiết địa chỉ E',
        businessType: 'Bán lẻ',
        businessCategory: 'Điện thoại',
        displayOrder: 5,
        transactionLevel: 2,
        brandId: 'BRAND05',
        brandName: 'Thương hiệu E',
        viettelId: 'ViettelE',
        viettelPassword: 'passwordE',
        templateCode: 'TEMP05',
        invoiceSeries: 'INV005',
    },
    {
        key: '5',
        storeCode: '00006',
        storeType: 'Wholesale',
        transactionType: 'Credit',
        name: 'Cửa hàng F',
        representative: 'Trần Thị F',
        representativeId: 'REP06',
        phoneNumber: '0123456784',
        faxNumber: '0987654316',
        email: 'exampleF@mail.com',
        homepage: 'http://storeF.com',
        totalArea: 190,
        storeArea: 140,
        parkingSpaces: 28,
        employeeCount: 9,
        bankName: 'Ngân hàng F',
        accountNumber: '789123456',
        accountHolder: 'Trần Thị F',
        transactionStartDate: new Date('2023-06-01'),
        transactionEndDate: new Date('2024-06-01'),
        businessNumber1: '789',
        businessNumber2: '12',
        businessNumber3: '34567',
        postalCode: '600000',
        address: 'Địa chỉ F',
        detailedAddress: 'Chi tiết địa chỉ F',
        businessType: 'Bán buôn',
        businessCategory: 'Thời trang',
        displayOrder: 6,
        transactionLevel: 3,
        brandId: 'BRAND06',
        brandName: 'Thương hiệu F',
        viettelId: 'ViettelF',
        viettelPassword: 'passwordF',
        templateCode: 'TEMP06',
        invoiceSeries: 'INV006',
    },
    {
        key: '6',
        storeCode: '00007',
        storeType: 'Franchise',
        transactionType: 'Cash',
        name: 'Cửa hàng G',
        representative: 'Lê Văn G',
        representativeId: 'REP07',
        phoneNumber: '0123456783',
        faxNumber: '0987654315',
        email: 'exampleG@mail.com',
        homepage: 'http://storeG.com',
        totalArea: 170,
        storeArea: 130,
        parkingSpaces: 18,
        employeeCount: 7,
        bankName: 'Ngân hàng G',
        accountNumber: '321321321',
        accountHolder: 'Lê Văn G',
        transactionStartDate: new Date('2023-07-01'),
        transactionEndDate: new Date('2024-07-01'),
        businessNumber1: '321',
        businessNumber2: '21',
        businessNumber3: '12345',
        postalCode: '700000',
        address: 'Địa chỉ G',
        detailedAddress: 'Chi tiết địa chỉ G',
        businessType: 'Nhượng quyền',
        businessCategory: 'Thực phẩm',
        displayOrder: 7,
        transactionLevel: 1,
        brandId: 'BRAND07',
        brandName: 'Thương hiệu G',
        viettelId: 'ViettelG',
        viettelPassword: 'passwordG',
        templateCode: 'TEMP07',
        invoiceSeries: 'INV007',
    },
    {
        key: '7',
        storeCode: '00008',
        storeType: 'Online',
        transactionType: 'Credit',
        name: 'Cửa hàng H',
        representative: 'Nguyễn Văn H',
        representativeId: 'REP08',
        phoneNumber: '0123456782',
        faxNumber: '0987654314',
        email: 'exampleH@mail.com',
        homepage: 'http://storeH.com',
        totalArea: 130,
        storeArea: 90,
        parkingSpaces: 12,
        employeeCount: 4,
        bankName: 'Ngân hàng H',
        accountNumber: '654654654',
        accountHolder: 'Nguyễn Văn H',
        transactionStartDate: new Date('2023-08-01'),
        transactionEndDate: new Date('2024-08-01'),
        businessNumber1: '654',
        businessNumber2: '12',
        businessNumber3: '98765',
        postalCode: '800000',
        address: 'Địa chỉ H',
        detailedAddress: 'Chi tiết địa chỉ H',
        businessType: 'Bán hàng trực tuyến',
        businessCategory: 'Sách',
        displayOrder: 8,
        transactionLevel: 2,
        brandId: 'BRAND08',
        brandName: 'Thương hiệu H',
        viettelId: 'ViettelH',
        viettelPassword: 'passwordH',
        templateCode: 'TEMP08',
        invoiceSeries: 'INV008',
    },
    {
        key: '8',
        storeCode: '00009',
        storeType: 'Retail',
        transactionType: 'Cash',
        name: 'Cửa hàng I',
        representative: 'Trần Văn I',
        representativeId: 'REP09',
        phoneNumber: '0123456781',
        faxNumber: '0987654313',
        email: 'exampleI@mail.com',
        homepage: 'http://storeI.com',
        totalArea: 140,
        storeArea: 100,
        parkingSpaces: 20,
        employeeCount: 5,
        bankName: 'Ngân hàng I',
        accountNumber: '789789789',
        accountHolder: 'Trần Văn I',
        transactionStartDate: new Date('2023-09-01'),
        transactionEndDate: new Date('2024-09-01'),
        businessNumber1: '789',
        businessNumber2: '78',
        businessNumber3: '23456',
        postalCode: '900000',
        address: 'Địa chỉ I',
        detailedAddress: 'Chi tiết địa chỉ I',
        businessType: 'Bán lẻ',
        businessCategory: 'Điện tử',
        displayOrder: 9,
        transactionLevel: 3,
        brandId: 'BRAND09',
        brandName: 'Thương hiệu I',
        viettelId: 'ViettelI',
        viettelPassword: 'passwordI',
        templateCode: 'TEMP09',
        invoiceSeries: 'INV009',
    },
    {
        key: '10',
        storeCode: '00010',
        storeType: 'Wholesale',
        transactionType: 'Credit',
        name: 'Cửa hàng J',
        representative: 'Nguyễn Thị J',
        representativeId: 'REP10',
        phoneNumber: '0123456780',
        faxNumber: '0987654312',
        email: 'exampleJ@mail.com',
        homepage: 'http://storeJ.com',
        totalArea: 210,
        storeArea: 160,
        parkingSpaces: 35,
        employeeCount: 12,
        bankName: 'Ngân hàng J',
        accountNumber: '321987654',
        accountHolder: 'Nguyễn Thị J',
        transactionStartDate: new Date('2023-10-01'),
        transactionEndDate: new Date('2024-10-01'),
        businessNumber1: '321',
        businessNumber2: '98',
        businessNumber3: '12345',
        postalCode: '1000000',
        address: 'Địa chỉ J',
        detailedAddress: 'Chi tiết địa chỉ J',
        businessType: 'Bán buôn',
        businessCategory: 'Thực phẩm',
        displayOrder: 10,
        transactionLevel: 1,
        brandId: 'BRAND10',
        brandName: 'Thương hiệu J',
        viettelId: 'ViettelJ',
        viettelPassword: 'passwordJ',
        templateCode: 'TEMP10',
        invoiceSeries: 'INV010',
    },
];
