export const storeListFake = [
    {
        key: '0',
        storeCode: '00001',
        storeType: 'Retail',
        transactionType: 'Cash',
        name: 'Cửa hàng A',
        representative: 'Nguyễn Văn A',
        representativeId: 'REP01',
        phoneNumber: '0123456789',
        faxNumber: '0987654321',
        email: 'exampleA@mail.com',
        homepage: 'http://storeA.com',
        totalArea: 150,
        storeArea: 100,
        parkingSpaces: 20,
        employeeCount: 5,
        bankName: 'Ngân hàng A',
        accountNumber: '123456789',
        accountHolder: 'Nguyễn Văn A',
        transactionStartDate: new Date('2023-01-01'),
        transactionEndDate: new Date('2024-01-01'),
        businessNumber1: '123',
        businessNumber2: '45',
        businessNumber3: '67890',
        postalCode: '100000',
        address: 'Địa chỉ A',
        detailedAddress: 'Chi tiết địa chỉ A',
        businessType: 'Bán lẻ',
        businessCategory: 'Thời trang',
        displayOrder: 1,
        transactionLevel: 1,
        brandId: 'BRAND01',
        brandName: 'Thương hiệu A',
        viettelId: 'ViettelA',
        viettelPassword: 'passwordA',
        templateCode: 'TEMP01',
        invoiceSeries: 'INV001',
    },
    {
        key: '1',
        storeCode: '00002',
        storeType: 'Wholesale',
        transactionType: 'Credit',
        name: 'Cửa hàng B',
        representative: 'Trần Văn B',
        representativeId: 'REP02',
        phoneNumber: '0123456788',
        faxNumber: '0987654320',
        email: 'exampleB@mail.com',
        homepage: 'http://storeB.com',
        totalArea: 200,
        storeArea: 150,
        parkingSpaces: 30,
        employeeCount: 10,
        bankName: 'Ngân hàng B',
        accountNumber: '987654321',
        accountHolder: 'Trần Văn B',
        transactionStartDate: new Date('2023-02-01'),
        transactionEndDate: new Date('2024-02-01'),
        businessNumber1: '987',
        businessNumber2: '65',
        businessNumber3: '43210',
        postalCode: '200000',
        address: 'Địa chỉ B',
        detailedAddress: 'Chi tiết địa chỉ B',
        businessType: 'Bán buôn',
        businessCategory: 'Điện máy',
        displayOrder: 2,
        transactionLevel: 2,
        brandId: 'BRAND02',
        brandName: 'Thương hiệu B',
        viettelId: 'ViettelB',
        viettelPassword: 'passwordB',
        templateCode: 'TEMP02',
        invoiceSeries: 'INV002',
    },
    {
        key: '2',
        storeCode: '00003',
        storeType: 'Franchise',
        transactionType: 'Cash',
        name: 'Cửa hàng C',
        representative: 'Lê Văn C',
        representativeId: 'REP03',
        phoneNumber: '0123456787',
        faxNumber: '0987654319',
        email: 'exampleC@mail.com',
        homepage: 'http://storeC.com',
        totalArea: 180,
        storeArea: 120,
        parkingSpaces: 25,
        employeeCount: 8,
        bankName: 'Ngân hàng C',
        accountNumber: '456789123',
        accountHolder: 'Lê Văn C',
        transactionStartDate: new Date('2023-03-01'),
        transactionEndDate: new Date('2024-03-01'),
        businessNumber1: '456',
        businessNumber2: '78',
        businessNumber3: '12345',
        postalCode: '300000',
        address: 'Địa chỉ C',
        detailedAddress: 'Chi tiết địa chỉ C',
        businessType: 'Nhượng quyền',
        businessCategory: 'Thực phẩm',
        displayOrder: 3,
        transactionLevel: 3,
        brandId: 'BRAND03',
        brandName: 'Thương hiệu C',
        viettelId: 'ViettelC',
        viettelPassword: 'passwordC',
        templateCode: 'TEMP03',
        invoiceSeries: 'INV003',
    },
    {
        key: '3',
        storeCode: '00004',
        storeType: 'Online',
        transactionType: 'Credit',
        name: 'Cửa hàng D',
        representative: 'Phạm Văn D',
        representativeId: 'REP04',
        phoneNumber: '0123456786',
        faxNumber: '0987654318',
        email: 'exampleD@mail.com',
        homepage: 'http://storeD.com',
        totalArea: 120,
        storeArea: 80,
        parkingSpaces: 15,
        employeeCount: 3,
        bankName: 'Ngân hàng D',
        accountNumber: '321654987',
        accountHolder: 'Phạm Văn D',
        transactionStartDate: new Date('2023-04-01'),
        transactionEndDate: new Date('2024-04-01'),
        businessNumber1: '321',
        businessNumber2: '65',
        businessNumber3: '98765',
        postalCode: '400000',
        address: 'Địa chỉ D',
        detailedAddress: 'Chi tiết địa chỉ D',
        businessType: 'Bán hàng trực tuyến',
        businessCategory: 'Sách',
        displayOrder: 4,
        transactionLevel: 1,
        brandId: 'BRAND04',
        brandName: 'Thương hiệu D',
        viettelId: 'ViettelD',
        viettelPassword: 'passwordD',
        templateCode: 'TEMP04',
        invoiceSeries: 'INV004',
    },
    {
        key: '4',
        storeCode: '00005',
        storeType: 'Retail',
        transactionType: 'Cash',
        name: 'Cửa hàng E',
        representative: 'Nguyễn Thị E',
        representativeId: 'REP05',
        phoneNumber: '0123456785',
        faxNumber: '0987654317',
        email: 'exampleE@mail.com',
        homepage: 'http://storeE.com',
        totalArea: 160,
        storeArea: 110,
        parkingSpaces: 22,
        employeeCount: 6,
        bankName: 'Ngân hàng E',
        accountNumber: '654789321',
        accountHolder: 'Nguyễn Thị E',
        transactionStartDate: new Date('2023-05-01'),
        transactionEndDate: new Date('2024-05-01'),
        businessNumber1: '654',
        businessNumber2: '32',
        businessNumber3: '54321',
        postalCode: '500000',
        address: 'Địa chỉ E',
        detailedAddress: 'Chi tiết địa chỉ E',
        businessType: 'Bán lẻ',
        businessCategory: 'Điện thoại',
        displayOrder: 5,
        transactionLevel: 2,
        brandId: 'BRAND05',
        brandName: 'Thương hiệu E',
        viettelId: 'ViettelE',
        viettelPassword: 'passwordE',
        templateCode: 'TEMP05',
        invoiceSeries: 'INV005',
    },
    {
        key: '5',
        storeCode: '00006',
        storeType: 'Wholesale',
        transactionType: 'Credit',
        name: 'Cửa hàng F',
        representative: 'Trần Thị F',
        representativeId: 'REP06',
        phoneNumber: '0123456784',
        faxNumber: '0987654316',
        email: 'exampleF@mail.com',
        homepage: 'http://storeF.com',
        totalArea: 190,
        storeArea: 140,
        parkingSpaces: 28,
        employeeCount: 9,
        bankName: 'Ngân hàng F',
        accountNumber: '789123456',
        accountHolder: 'Trần Thị F',
        transactionStartDate: new Date('2023-06-01'),
        transactionEndDate: new Date('2024-06-01'),
        businessNumber1: '789',
        businessNumber2: '12',
        businessNumber3: '34567',
        postalCode: '600000',
        address: 'Địa chỉ F',
        detailedAddress: 'Chi tiết địa chỉ F',
        businessType: 'Bán buôn',
        businessCategory: 'Thời trang',
        displayOrder: 6,
        transactionLevel: 3,
        brandId: 'BRAND06',
        brandName: 'Thương hiệu F',
        viettelId: 'ViettelF',
        viettelPassword: 'passwordF',
        templateCode: 'TEMP06',
        invoiceSeries: 'INV006',
    },
    {
        key: '6',
        storeCode: '00007',
        storeType: 'Franchise',
        transactionType: 'Cash',
        name: 'Cửa hàng G',
        representative: 'Lê Văn G',
        representativeId: 'REP07',
        phoneNumber: '0123456783',
        faxNumber: '0987654315',
        email: 'exampleG@mail.com',
        homepage: 'http://storeG.com',
        totalArea: 170,
        storeArea: 130,
        parkingSpaces: 18,
        employeeCount: 7,
        bankName: 'Ngân hàng G',
        accountNumber: '321321321',
        accountHolder: 'Lê Văn G',
        transactionStartDate: new Date('2023-07-01'),
        transactionEndDate: new Date('2024-07-01'),
        businessNumber1: '321',
        businessNumber2: '21',
        businessNumber3: '12345',
        postalCode: '700000',
        address: 'Địa chỉ G',
        detailedAddress: 'Chi tiết địa chỉ G',
        businessType: 'Nhượng quyền',
        businessCategory: 'Thực phẩm',
        displayOrder: 7,
        transactionLevel: 1,
        brandId: 'BRAND07',
        brandName: 'Thương hiệu G',
        viettelId: 'ViettelG',
        viettelPassword: 'passwordG',
        templateCode: 'TEMP07',
        invoiceSeries: 'INV007',
    },
    {
        key: '7',
        storeCode: '00008',
        storeType: 'Online',
        transactionType: 'Credit',
        name: 'Cửa hàng H',
        representative: 'Nguyễn Văn H',
        representativeId: 'REP08',
        phoneNumber: '0123456782',
        faxNumber: '0987654314',
        email: 'exampleH@mail.com',
        homepage: 'http://storeH.com',
        totalArea: 130,
        storeArea: 90,
        parkingSpaces: 12,
        employeeCount: 4,
        bankName: 'Ngân hàng H',
        accountNumber: '654654654',
        accountHolder: 'Nguyễn Văn H',
        transactionStartDate: new Date('2023-08-01'),
        transactionEndDate: new Date('2024-08-01'),
        businessNumber1: '654',
        businessNumber2: '12',
        businessNumber3: '98765',
        postalCode: '800000',
        address: 'Địa chỉ H',
        detailedAddress: 'Chi tiết địa chỉ H',
        businessType: 'Bán hàng trực tuyến',
        businessCategory: 'Sách',
        displayOrder: 8,
        transactionLevel: 2,
        brandId: 'BRAND08',
        brandName: 'Thương hiệu H',
        viettelId: 'ViettelH',
        viettelPassword: 'passwordH',
        templateCode: 'TEMP08',
        invoiceSeries: 'INV008',
    },
    {
        key: '8',
        storeCode: '00009',
        storeType: 'Retail',
        transactionType: 'Cash',
        name: 'Cửa hàng I',
        representative: 'Trần Văn I',
        representativeId: 'REP09',
        phoneNumber: '0123456781',
        faxNumber: '0987654313',
        email: 'exampleI@mail.com',
        homepage: 'http://storeI.com',
        totalArea: 140,
        storeArea: 100,
        parkingSpaces: 20,
        employeeCount: 5,
        bankName: 'Ngân hàng I',
        accountNumber: '789789789',
        accountHolder: 'Trần Văn I',
        transactionStartDate: new Date('2023-09-01'),
        transactionEndDate: new Date('2024-09-01'),
        businessNumber1: '789',
        businessNumber2: '78',
        businessNumber3: '23456',
        postalCode: '900000',
        address: 'Địa chỉ I',
        detailedAddress: 'Chi tiết địa chỉ I',
        businessType: 'Bán lẻ',
        businessCategory: 'Điện tử',
        displayOrder: 9,
        transactionLevel: 3,
        brandId: 'BRAND09',
        brandName: 'Thương hiệu I',
        viettelId: 'ViettelI',
        viettelPassword: 'passwordI',
        templateCode: 'TEMP09',
        invoiceSeries: 'INV009',
    },
    {
        key: '10',
        storeCode: '00010',
        storeType: 'Wholesale',
        transactionType: 'Credit',
        name: 'Cửa hàng J',
        representative: 'Nguyễn Thị J',
        representativeId: 'REP10',
        phoneNumber: '0123456780',
        faxNumber: '0987654312',
        email: 'exampleJ@mail.com',
        homepage: 'http://storeJ.com',
        totalArea: 210,
        storeArea: 160,
        parkingSpaces: 35,
        employeeCount: 12,
        bankName: 'Ngân hàng J',
        accountNumber: '321987654',
        accountHolder: 'Nguyễn Thị J',
        transactionStartDate: new Date('2023-10-01'),
        transactionEndDate: new Date('2024-10-01'),
        businessNumber1: '321',
        businessNumber2: '98',
        businessNumber3: '12345',
        postalCode: '1000000',
        address: 'Địa chỉ J',
        detailedAddress: 'Chi tiết địa chỉ J',
        businessType: 'Bán buôn',
        businessCategory: 'Thực phẩm',
        displayOrder: 10,
        transactionLevel: 1,
        brandId: 'BRAND10',
        brandName: 'Thương hiệu J',
        viettelId: 'ViettelJ',
        viettelPassword: 'passwordJ',
        templateCode: 'TEMP10',
        invoiceSeries: 'INV010',
    },
];

export const productListFake = [
    {
        barcode: 'K0001',
        productName: '1. Một con lợn 돼지 한 마리',
        shortName: '1. Một con lợn 돼지 한 마리',
        specification: '',
        unit: 'Suất',
        color: '',
        transactionType: '정상거래',
        taxCode: 'D10101',
        businessCode: '00001',
        inBoxQuantity: 0,
        outBoxQuantity: 0,
        catonBoxQuantity: 0,
        inBoxCode: '',
        outBoxCode: '',
        catonBoxCode: '',
        taxType: '8',
        purchasePrice: 0,
        purchaseTax: 0,
        purchaseAmount: 0,
        profitMargin: 100.0,
        sellingPrice: 1200000,
        sellingTax: 96000,
        sellingAmount: 1296000,
        consumerPrice: 0,
        wholesalePrice1: 0,
        wholesalePrice2: 0,
        wholesalePrice3: 0,
        wholesalePrice4: 0,
        wholesalePrice5: 0,
        wholesalePrice6: 0,
        wholesalePrice7: 0,
        wholesalePrice8: 0,
        wholesalePrice9: 0,
        wholesalePrice10: 0,
        discountedPurchasePrice: 0,
        discountedPurchaseTax: 0,
        discountedPurchaseAmount: 0,
        discountedProfitMargin: 0,
        discountedSellingPrice: 0,
        discountedSellingTax: 0,
        discountedSellingAmount: 0,
        discountStartDate: '2000-01-01T00:00:00',
        discountEndDate: '2000-01-01T00:00:00',
        orderUnit: 'EA',
        pointApplication: 'True',
        pointScore: 0,
        memberPriceApplication: 'False',
        memberPrice: 0,
        memberTax: 0,
        memberAmount: 0,
        transactionStartDate: '2000-01-01T00:00:00',
        transactionEndDate: '2100-12-31T00:00:00',
        inBoxSellingAmount: 0,
        outBoxSellingAmount: 0,
        catonBoxSellingAmount: 0,
        modifiedDate: '2024-07-24T11:20:14',
        remarks: '',
        sellingPurchase: false,
        emptyBottleCode: '',
        productType: '주방조리',
        isDeleted: false,
        modifiedBy: '1111',
        createdBy: '1111',
        createdDate: '2024-07-24T11:20:14',
        taxName: 'Tax 8',
        storeName: 'HYOJUNG2',
    },
    {
        barcode: 'S017',
        productName: '7up/ cola (사이다/ 콜라)',
        shortName: '7up/ cola (사이다/ 콜라)',
        specification: '',
        unit: 'Lon',
        color: '',
        transactionType: '정상거래',
        taxCode: 'M10101',
        businessCode: '00001',
        inBoxQuantity: 0,
        outBoxQuantity: 0,
        catonBoxQuantity: 0,
        inBoxCode: '0',
        outBoxCode: '0',
        catonBoxCode: '0',
        taxType: '8',
        purchasePrice: 0,
        purchaseTax: 0,
        purchaseAmount: 0,
        profitMargin: 100.0,
        sellingPrice: 20000,
        sellingTax: 1600,
        sellingAmount: 21600,
        consumerPrice: 0,
        wholesalePrice1: 0,
        wholesalePrice2: 0,
        wholesalePrice3: 0,
        wholesalePrice4: 0,
        wholesalePrice5: 0,
        wholesalePrice6: 0,
        wholesalePrice7: 0,
        wholesalePrice8: 0,
        wholesalePrice9: 0,
        wholesalePrice10: 0,
        discountedPurchasePrice: 0,
        discountedPurchaseTax: 0,
        discountedPurchaseAmount: 0,
        discountedProfitMargin: 0,
        discountedSellingPrice: 0,
        discountedSellingTax: 0,
        discountedSellingAmount: 0,
        discountStartDate: '2000-01-01T00:00:00',
        discountEndDate: '2000-01-01T00:00:00',
        orderUnit: 'EA',
        pointApplication: 'True',
        pointScore: 0,
        memberPriceApplication: 'False',
        memberPrice: 0,
        memberTax: 0,
        memberAmount: 0,
        transactionStartDate: '2000-01-01T00:00:00',
        transactionEndDate: '2100-12-31T00:00:00',
        inBoxSellingAmount: 0,
        outBoxSellingAmount: 0,
        catonBoxSellingAmount: 0,
        modifiedDate: '2022-05-10T15:48:05.03',
        remarks: '',
        sellingPurchase: false,
        emptyBottleCode: '',
        productType: '주방조리',
        isDeleted: false,
        modifiedBy: '1111',
        createdBy: '1111',
        createdDate: '2021-07-17T02:38:39.03',
        taxName: 'Ruou,Bia',
        storeName: 'HYOJUNG2',
    },
    {
        barcode: '001',
        productName: '돼지불백',
        shortName: '돼지불백',
        specification: '',
        unit: '',
        color: '',
        transactionType: '정상거래',
        taxCode: 'D10101',
        businessCode: '0000000',
        inBoxQuantity: 0,
        outBoxQuantity: 0,
        catonBoxQuantity: 0,
        inBoxCode: '',
        outBoxCode: '',
        catonBoxCode: '',
        taxType: '8',
        purchasePrice: 0,
        purchaseTax: 0,
        purchaseAmount: 0,
        profitMargin: 0.0,
        sellingPrice: 2000000,
        sellingTax: 0,
        sellingAmount: 0,
        consumerPrice: 0,
        wholesalePrice1: 0,
        wholesalePrice2: 0,
        wholesalePrice3: 0,
        wholesalePrice4: 0,
        wholesalePrice5: 0,
        wholesalePrice6: 0,
        wholesalePrice7: 0,
        wholesalePrice8: 0,
        wholesalePrice9: 0,
        wholesalePrice10: 0,
        discountedPurchasePrice: 0,
        discountedPurchaseTax: 0,
        discountedPurchaseAmount: 0,
        discountedProfitMargin: 0,
        discountedSellingPrice: 0,
        discountedSellingTax: 0,
        discountedSellingAmount: 0,
        discountStartDate: '2000-01-01T00:00:00',
        discountEndDate: '2000-01-01T00:00:00',
        orderUnit: 'EA',
        pointApplication: 'False',
        pointScore: 0,
        memberPriceApplication: 'False',
        memberPrice: 0,
        memberTax: 0,
        memberAmount: 0,
        transactionStartDate: '2000-01-01T00:00:00',
        transactionEndDate: '2100-12-31T00:00:00',
        inBoxSellingAmount: 0,
        outBoxSellingAmount: 0,
        catonBoxSellingAmount: 0,
        modifiedDate: '2024-09-16T13:25:17',
        remarks: '',
        sellingPurchase: false,
        emptyBottleCode: '',
        productType: '일반상품',
        isDeleted: false,
        modifiedBy: '1111',
        createdBy: '1111',
        createdDate: '2024-09-16T13:25:17',
        taxName: 'Tax 8',
        storeName: null,
    },
    {
        barcode: '8806427000911',
        productName: 'A le',
        shortName: 'A le',
        specification: '',
        unit: 'Chai',
        color: '',
        transactionType: '정상거래',
        taxCode: 'D10102',
        businessCode: '00001',
        inBoxQuantity: 10,
        outBoxQuantity: 0,
        catonBoxQuantity: 0,
        inBoxCode: '18806427000918',
        outBoxCode: '',
        catonBoxCode: '',
        taxType: '10',
        purchasePrice: 32000,
        purchaseTax: 0,
        purchaseAmount: 32000,
        profitMargin: 15.79,
        sellingPrice: 38000,
        sellingTax: 0,
        sellingAmount: 38000,
        consumerPrice: 0,
        wholesalePrice1: 0,
        wholesalePrice2: 0,
        wholesalePrice3: 0,
        wholesalePrice4: 0,
        wholesalePrice5: 0,
        wholesalePrice6: 0,
        wholesalePrice7: 0,
        wholesalePrice8: 0,
        wholesalePrice9: 0,
        wholesalePrice10: 0,
        discountedPurchasePrice: 0,
        discountedPurchaseTax: 0,
        discountedPurchaseAmount: 0,
        discountedProfitMargin: 0,
        discountedSellingPrice: 0,
        discountedSellingTax: 0,
        discountedSellingAmount: 0,
        discountStartDate: '2000-01-01T00:00:00',
        discountEndDate: '2000-01-01T00:00:00',
        orderUnit: 'EA',
        pointApplication: 'False',
        pointScore: 0,
        memberPriceApplication: 'False',
        memberPrice: 0,
        memberTax: 0,
        memberAmount: 0,
        transactionStartDate: '2000-01-01T00:00:00',
        transactionEndDate: '2100-12-31T00:00:00',
        inBoxSellingAmount: 380000,
        outBoxSellingAmount: 0,
        catonBoxSellingAmount: 0,
        modifiedDate: '2025-01-17T11:50:22',
        remarks: '',
        sellingPurchase: false,
        emptyBottleCode: '',
        productType: '일반상품',
        isDeleted: false,
        modifiedBy: '1111',
        createdBy: '1111',
        createdDate: '2025-01-17T11:49:05',
        taxName: 'Tax 10',
        storeName: 'HYOJUNG2',
    },
    {
        barcode: 'D0010',
        productName: 'Aquafina',
        shortName: 'Aquafina',
        specification: '',
        unit: 'Chai',
        color: '',
        transactionType: '정상거래',
        taxCode: 'D10102',
        businessCode: '00001',
        inBoxQuantity: 0,
        outBoxQuantity: 0,
        catonBoxQuantity: 0,
        inBoxCode: '',
        outBoxCode: '',
        catonBoxCode: '',
        taxType: '8',
        purchasePrice: 0,
        purchaseTax: 0,
        purchaseAmount: 0,
        profitMargin: 100.0,
        sellingPrice: 10000,
        sellingTax: 800,
        sellingAmount: 10800,
        consumerPrice: 0,
        wholesalePrice1: 0,
        wholesalePrice2: 0,
        wholesalePrice3: 0,
        wholesalePrice4: 0,
        wholesalePrice5: 0,
        wholesalePrice6: 0,
        wholesalePrice7: 0,
        wholesalePrice8: 0,
        wholesalePrice9: 0,
        wholesalePrice10: 0,
        discountedPurchasePrice: 0,
        discountedPurchaseTax: 0,
        discountedPurchaseAmount: 0,
        discountedProfitMargin: 0,
        discountedSellingPrice: 0,
        discountedSellingTax: 0,
        discountedSellingAmount: 0,
        discountStartDate: '2000-01-01T00:00:00',
        discountEndDate: '2000-01-01T00:00:00',
        orderUnit: 'EA',
        pointApplication: 'True',
        pointScore: 0,
        memberPriceApplication: 'False',
        memberPrice: 0,
        memberTax: 0,
        memberAmount: 0,
        transactionStartDate: '2000-01-01T00:00:00',
        transactionEndDate: '2100-12-31T00:00:00',
        inBoxSellingAmount: 0,
        outBoxSellingAmount: 0,
        catonBoxSellingAmount: 0,
        modifiedDate: '2023-07-06T23:17:34',
        remarks: '',
        sellingPurchase: false,
        emptyBottleCode: '',
        productType: '주방조리',
        isDeleted: false,
        modifiedBy: '0099',
        createdBy: '1111',
        createdDate: '2021-11-04T20:15:21',
        taxName: 'Tax 10',
        storeName: 'HYOJUNG2',
    },
    {
        barcode: 'VL103',
        productName: 'BÀN 1 NGƯỜI',
        shortName: 'BÀN 1 NGƯỜI',
        specification: '',
        unit: 'SUẤT',
        color: '',
        transactionType: '정상거래',
        taxCode: 'D10101',
        businessCode: '00001',
        inBoxQuantity: 0,
        outBoxQuantity: 0,
        catonBoxQuantity: 0,
        inBoxCode: '',
        outBoxCode: '',
        catonBoxCode: '',
        taxType: '8',
        purchasePrice: 0,
        purchaseTax: 0,
        purchaseAmount: 0,
        profitMargin: 100.0,
        sellingPrice: 0,
        sellingTax: 0,
        sellingAmount: 0,
        consumerPrice: 0,
        wholesalePrice1: 0,
        wholesalePrice2: 0,
        wholesalePrice3: 0,
        wholesalePrice4: 0,
        wholesalePrice5: 0,
        wholesalePrice6: 0,
        wholesalePrice7: 0,
        wholesalePrice8: 0,
        wholesalePrice9: 0,
        wholesalePrice10: 0,
        discountedPurchasePrice: 0,
        discountedPurchaseTax: 0,
        discountedPurchaseAmount: 0,
        discountedProfitMargin: 0,
        discountedSellingPrice: 0,
        discountedSellingTax: 0,
        discountedSellingAmount: 0,
        discountStartDate: '2000-01-01T00:00:00',
        discountEndDate: '2000-01-01T00:00:00',
        orderUnit: 'EA',
        pointApplication: 'False',
        pointScore: 0,
        memberPriceApplication: 'False',
        memberPrice: 0,
        memberTax: 0,
        memberAmount: 0,
        transactionStartDate: '2000-01-01T00:00:00',
        transactionEndDate: '2100-12-31T00:00:00',
        inBoxSellingAmount: 0,
        outBoxSellingAmount: 0,
        catonBoxSellingAmount: 0,
        modifiedDate: '2024-08-27T11:27:17',
        remarks: '',
        sellingPurchase: false,
        emptyBottleCode: '',
        productType: '주방조리',
        isDeleted: false,
        modifiedBy: '1111',
        createdBy: '1111',
        createdDate: '2024-08-27T11:27:17',
        taxName: 'Tax 8',
        storeName: 'HYOJUNG2',
    },
    {
        barcode: 'VL104',
        productName: 'BÀN 2 NGƯỜI',
        shortName: 'BÀN 2 NGƯỜI',
        specification: '',
        unit: 'SUẤT',
        color: '',
        transactionType: '정상거래',
        taxCode: 'D10101',
        businessCode: '00001',
        inBoxQuantity: 0,
        outBoxQuantity: 0,
        catonBoxQuantity: 0,
        inBoxCode: '',
        outBoxCode: '',
        catonBoxCode: '',
        taxType: '8',
        purchasePrice: 0,
        purchaseTax: 0,
        purchaseAmount: 0,
        profitMargin: 100.0,
        sellingPrice: 0,
        sellingTax: 0,
        sellingAmount: 0,
        consumerPrice: 0,
        wholesalePrice1: 0,
        wholesalePrice2: 0,
        wholesalePrice3: 0,
        wholesalePrice4: 0,
        wholesalePrice5: 0,
        wholesalePrice6: 0,
        wholesalePrice7: 0,
        wholesalePrice8: 0,
        wholesalePrice9: 0,
        wholesalePrice10: 0,
        discountedPurchasePrice: 0,
        discountedPurchaseTax: 0,
        discountedPurchaseAmount: 0,
        discountedProfitMargin: 0,
        discountedSellingPrice: 0,
        discountedSellingTax: 0,
        discountedSellingAmount: 0,
        discountStartDate: '2000-01-01T00:00:00',
        discountEndDate: '2000-01-01T00:00:00',
        orderUnit: 'EA',
        pointApplication: 'False',
        pointScore: 0,
        memberPriceApplication: 'False',
        memberPrice: 0,
        memberTax: 0,
        memberAmount: 0,
        transactionStartDate: '2000-01-01T00:00:00',
        transactionEndDate: '2100-12-31T00:00:00',
        inBoxSellingAmount: 0,
        outBoxSellingAmount: 0,
        catonBoxSellingAmount: 0,
        modifiedDate: '2024-08-27T11:27:52',
        remarks: '',
        sellingPurchase: false,
        emptyBottleCode: '',
        productType: '주방조리',
        isDeleted: false,
        modifiedBy: '1111',
        createdBy: '1111',
        createdDate: '2024-08-27T11:27:52',
        taxName: 'Tax 8',
        storeName: 'HYOJUNG2',
    },
    {
        barcode: 'S022',
        productName: 'Bánh bao (찐만두)',
        shortName: 'Bánh bao (찐만두)',
        specification: '',
        unit: 'Suất',
        color: '',
        transactionType: '정상거래',
        taxCode: 'M10101',
        businessCode: '00001',
        inBoxQuantity: 0,
        outBoxQuantity: 0,
        catonBoxQuantity: 0,
        inBoxCode: '0',
        outBoxCode: '0',
        catonBoxCode: '0',
        taxType: '8',
        purchasePrice: 0,
        purchaseTax: 0,
        purchaseAmount: 0,
        profitMargin: 100.0,
        sellingPrice: 100000,
        sellingTax: 8000,
        sellingAmount: 108000,
        consumerPrice: 0,
        wholesalePrice1: 0,
        wholesalePrice2: 0,
        wholesalePrice3: 0,
        wholesalePrice4: 0,
        wholesalePrice5: 0,
        wholesalePrice6: 0,
        wholesalePrice7: 0,
        wholesalePrice8: 0,
        wholesalePrice9: 0,
        wholesalePrice10: 0,
        discountedPurchasePrice: 0,
        discountedPurchaseTax: 0,
        discountedPurchaseAmount: 0,
        discountedProfitMargin: 0,
        discountedSellingPrice: 0,
        discountedSellingTax: 0,
        discountedSellingAmount: 0,
        discountStartDate: '2000-01-01T00:00:00',
        discountEndDate: '2000-01-01T00:00:00',
        orderUnit: 'EA',
        pointApplication: 'True',
        pointScore: 0,
        memberPriceApplication: 'False',
        memberPrice: 0,
        memberTax: 0,
        memberAmount: 0,
        transactionStartDate: '2000-01-01T00:00:00',
        transactionEndDate: '2100-12-31T00:00:00',
        inBoxSellingAmount: 0,
        outBoxSellingAmount: 0,
        catonBoxSellingAmount: 0,
        modifiedDate: '2023-06-12T15:21:06',
        remarks: '',
        sellingPurchase: false,
        emptyBottleCode: '',
        productType: '주방조리',
        isDeleted: false,
        modifiedBy: '1111',
        createdBy: '1111',
        createdDate: '2021-07-17T02:38:39.037',
        taxName: 'Ruou,Bia',
        storeName: 'HYOJUNG2',
    },
    {
        barcode: 'BB1',
        productName: 'Bánh bao chay',
        shortName: 'Bánh bao chay',
        specification: '',
        unit: 'cái',
        color: '',
        transactionType: '정상거래',
        taxCode: 'D10101',
        businessCode: '00001',
        inBoxQuantity: 0,
        outBoxQuantity: 0,
        catonBoxQuantity: 0,
        inBoxCode: '',
        outBoxCode: '',
        catonBoxCode: '',
        taxType: '8',
        purchasePrice: 0,
        purchaseTax: 0,
        purchaseAmount: 0,
        profitMargin: 100.0,
        sellingPrice: 50000,
        sellingTax: 4000,
        sellingAmount: 54000,
        consumerPrice: 0,
        wholesalePrice1: 0,
        wholesalePrice2: 0,
        wholesalePrice3: 0,
        wholesalePrice4: 0,
        wholesalePrice5: 0,
        wholesalePrice6: 0,
        wholesalePrice7: 0,
        wholesalePrice8: 0,
        wholesalePrice9: 0,
        wholesalePrice10: 0,
        discountedPurchasePrice: 0,
        discountedPurchaseTax: 0,
        discountedPurchaseAmount: 0,
        discountedProfitMargin: 0,
        discountedSellingPrice: 0,
        discountedSellingTax: 0,
        discountedSellingAmount: 0,
        discountStartDate: '2000-01-01T00:00:00',
        discountEndDate: '2000-01-01T00:00:00',
        orderUnit: 'EA',
        pointApplication: 'True',
        pointScore: 0,
        memberPriceApplication: 'False',
        memberPrice: 0,
        memberTax: 0,
        memberAmount: 0,
        transactionStartDate: '2000-01-01T00:00:00',
        transactionEndDate: '2100-12-31T00:00:00',
        inBoxSellingAmount: 0,
        outBoxSellingAmount: 0,
        catonBoxSellingAmount: 0,
        modifiedDate: '2024-08-09T10:16:20',
        remarks: '',
        sellingPurchase: false,
        emptyBottleCode: '',
        productType: '주방조리',
        isDeleted: false,
        modifiedBy: '1111',
        createdBy: '1111',
        createdDate: '2024-08-09T10:16:20',
        taxName: 'Tax 8',
        storeName: 'HYOJUNG2',
    },
    {
        barcode: 'abc',
        productName: 'bánh gà',
        shortName: 'bánh gà',
        specification: '',
        unit: 'suất ',
        color: '',
        transactionType: '정상거래',
        taxCode: 'D10101',
        businessCode: '00001',
        inBoxQuantity: 0,
        outBoxQuantity: 0,
        catonBoxQuantity: 0,
        inBoxCode: '',
        outBoxCode: '',
        catonBoxCode: '',
        taxType: '8',
        purchasePrice: 0,
        purchaseTax: 0,
        purchaseAmount: 0,
        profitMargin: 100.0,
        sellingPrice: 50000,
        sellingTax: 4000,
        sellingAmount: 54000,
        consumerPrice: 0,
        wholesalePrice1: 0,
        wholesalePrice2: 0,
        wholesalePrice3: 0,
        wholesalePrice4: 0,
        wholesalePrice5: 0,
        wholesalePrice6: 0,
        wholesalePrice7: 0,
        wholesalePrice8: 0,
        wholesalePrice9: 0,
        wholesalePrice10: 0,
        discountedPurchasePrice: 0,
        discountedPurchaseTax: 0,
        discountedPurchaseAmount: 0,
        discountedProfitMargin: 0,
        discountedSellingPrice: 0,
        discountedSellingTax: 0,
        discountedSellingAmount: 0,
        discountStartDate: '2000-01-01T00:00:00',
        discountEndDate: '2000-01-01T00:00:00',
        orderUnit: 'EA',
        pointApplication: 'True',
        pointScore: 0,
        memberPriceApplication: 'False',
        memberPrice: 0,
        memberTax: 0,
        memberAmount: 0,
        transactionStartDate: '2000-01-01T00:00:00',
        transactionEndDate: '2100-12-31T00:00:00',
        inBoxSellingAmount: 0,
        outBoxSellingAmount: 0,
        catonBoxSellingAmount: 0,
        modifiedDate: '2024-06-25T14:34:30',
        remarks: '',
        sellingPurchase: false,
        emptyBottleCode: '',
        productType: '주방조리',
        isDeleted: false,
        modifiedBy: '1111',
        createdBy: '1111',
        createdDate: '2024-06-25T14:30:04',
        taxName: 'Tax 8',
        storeName: 'HYOJUNG2',
    },
    {
        barcode: 'S002',
        productName: 'Bánh gạo (떡추가)',
        shortName: 'Bánh gạo (떡추가)',
        specification: '',
        unit: 'Suất',
        color: '',
        transactionType: '정상거래',
        taxCode: 'M10101',
        businessCode: '00001',
        inBoxQuantity: 0,
        outBoxQuantity: 0,
        catonBoxQuantity: 0,
        inBoxCode: '0',
        outBoxCode: '0',
        catonBoxCode: '0',
        taxType: '8',
        purchasePrice: 0,
        purchaseTax: 0,
        purchaseAmount: 0,
        profitMargin: 100.0,
        sellingPrice: 30000,
        sellingTax: 2400,
        sellingAmount: 32400,
        consumerPrice: 0,
        wholesalePrice1: 0,
        wholesalePrice2: 0,
        wholesalePrice3: 0,
        wholesalePrice4: 0,
        wholesalePrice5: 0,
        wholesalePrice6: 0,
        wholesalePrice7: 0,
        wholesalePrice8: 0,
        wholesalePrice9: 0,
        wholesalePrice10: 0,
        discountedPurchasePrice: 0,
        discountedPurchaseTax: 0,
        discountedPurchaseAmount: 0,
        discountedProfitMargin: 0,
        discountedSellingPrice: 0,
        discountedSellingTax: 0,
        discountedSellingAmount: 0,
        discountStartDate: '2000-01-01T00:00:00',
        discountEndDate: '2000-01-01T00:00:00',
        orderUnit: 'EA',
        pointApplication: 'True',
        pointScore: 0,
        memberPriceApplication: 'False',
        memberPrice: 0,
        memberTax: 0,
        memberAmount: 0,
        transactionStartDate: '2000-01-01T00:00:00',
        transactionEndDate: '2100-12-31T00:00:00',
        inBoxSellingAmount: 0,
        outBoxSellingAmount: 0,
        catonBoxSellingAmount: 0,
        modifiedDate: '2023-06-12T15:20:17',
        remarks: '',
        sellingPurchase: false,
        emptyBottleCode: '',
        productType: '주방조리',
        isDeleted: false,
        modifiedBy: '1111',
        createdBy: '1111',
        createdDate: '2021-07-17T02:38:39.037',
        taxName: 'Ruou,Bia',
        storeName: 'HYOJUNG2',
    },
    {
        barcode: 'S025',
        productName: 'Bánh gạo cay (소담 떡볶이)',
        shortName: 'Bánh gạo cay (소담 떡볶이)',
        specification: '',
        unit: 'Suất',
        color: '',
        transactionType: '정상거래',
        taxCode: 'M10101',
        businessCode: '00001',
        inBoxQuantity: 0,
        outBoxQuantity: 0,
        catonBoxQuantity: 0,
        inBoxCode: '0',
        outBoxCode: '0',
        catonBoxCode: '0',
        taxType: '8',
        purchasePrice: 0,
        purchaseTax: 0,
        purchaseAmount: 0,
        profitMargin: 100.0,
        sellingPrice: 150000,
        sellingTax: 12000,
        sellingAmount: 162000,
        consumerPrice: 0,
        wholesalePrice1: 0,
        wholesalePrice2: 0,
        wholesalePrice3: 0,
        wholesalePrice4: 0,
        wholesalePrice5: 0,
        wholesalePrice6: 0,
        wholesalePrice7: 0,
        wholesalePrice8: 0,
        wholesalePrice9: 0,
        wholesalePrice10: 0,
        discountedPurchasePrice: 0,
        discountedPurchaseTax: 0,
        discountedPurchaseAmount: 0,
        discountedProfitMargin: 0,
        discountedSellingPrice: 0,
        discountedSellingTax: 0,
        discountedSellingAmount: 0,
        discountStartDate: '2000-01-01T00:00:00',
        discountEndDate: '2000-01-01T00:00:00',
        orderUnit: 'EA',
        pointApplication: 'True',
        pointScore: 0,
        memberPriceApplication: 'False',
        memberPrice: 0,
        memberTax: 0,
        memberAmount: 0,
        transactionStartDate: '2000-01-01T00:00:00',
        transactionEndDate: '2100-12-31T00:00:00',
        inBoxSellingAmount: 0,
        outBoxSellingAmount: 0,
        catonBoxSellingAmount: 0,
        modifiedDate: '2023-06-12T15:22:47',
        remarks: '',
        sellingPurchase: false,
        emptyBottleCode: '',
        productType: '주방조리',
        isDeleted: false,
        modifiedBy: '1111',
        createdBy: '1111',
        createdDate: '2021-07-17T01:38:39.007',
        taxName: 'Ruou,Bia',
        storeName: 'HYOJUNG2',
    },
    {
        barcode: 'D0061',
        productName: 'Bánh Trứng',
        shortName: 'Egg Tart 에그타르트',
        specification: '',
        unit: 'Suất',
        color: '',
        transactionType: '정상거래',
        taxCode: 'D10103',
        businessCode: '00001',
        inBoxQuantity: 0,
        outBoxQuantity: 0,
        catonBoxQuantity: 0,
        inBoxCode: '',
        outBoxCode: '',
        catonBoxCode: '',
        taxType: '8',
        purchasePrice: 0,
        purchaseTax: 0,
        purchaseAmount: 0,
        profitMargin: 100.0,
        sellingPrice: 15000,
        sellingTax: 1200,
        sellingAmount: 16200,
        consumerPrice: 0,
        wholesalePrice1: 0,
        wholesalePrice2: 0,
        wholesalePrice3: 0,
        wholesalePrice4: 0,
        wholesalePrice5: 0,
        wholesalePrice6: 0,
        wholesalePrice7: 0,
        wholesalePrice8: 0,
        wholesalePrice9: 0,
        wholesalePrice10: 0,
        discountedPurchasePrice: 0,
        discountedPurchaseTax: 0,
        discountedPurchaseAmount: 0,
        discountedProfitMargin: 0,
        discountedSellingPrice: 0,
        discountedSellingTax: 0,
        discountedSellingAmount: 0,
        discountStartDate: '2000-01-01T00:00:00',
        discountEndDate: '2000-01-01T00:00:00',
        orderUnit: 'EA',
        pointApplication: 'True',
        pointScore: 0,
        memberPriceApplication: 'False',
        memberPrice: 0,
        memberTax: 0,
        memberAmount: 0,
        transactionStartDate: '2000-01-01T00:00:00',
        transactionEndDate: '2100-12-31T00:00:00',
        inBoxSellingAmount: 0,
        outBoxSellingAmount: 0,
        catonBoxSellingAmount: 0,
        modifiedDate: '2023-07-17T11:32:35',
        remarks: '',
        sellingPurchase: false,
        emptyBottleCode: '',
        productType: '주방조리',
        isDeleted: false,
        modifiedBy: '0099',
        createdBy: '0099',
        createdDate: '2023-07-17T10:07:29',
        taxName: 'Giao Hang',
        storeName: 'HYOJUNG2',
    },
    {
        barcode: 'D0062',
        productName: 'Bánh Trứng (Take Away)',
        shortName: 'Egg Tart 에그타르트 (Take Away)',
        specification: '',
        unit: 'Suất',
        color: '',
        transactionType: '정상거래',
        taxCode: 'D10103',
        businessCode: '00001',
        inBoxQuantity: 0,
        outBoxQuantity: 0,
        catonBoxQuantity: 0,
        inBoxCode: '',
        outBoxCode: '',
        catonBoxCode: '',
        taxType: '8',
        purchasePrice: 0,
        purchaseTax: 0,
        purchaseAmount: 0,
        profitMargin: 100.0,
        sellingPrice: 15000,
        sellingTax: 1200,
        sellingAmount: 16200,
        consumerPrice: 0,
        wholesalePrice1: 0,
        wholesalePrice2: 0,
        wholesalePrice3: 0,
        wholesalePrice4: 0,
        wholesalePrice5: 0,
        wholesalePrice6: 0,
        wholesalePrice7: 0,
        wholesalePrice8: 0,
        wholesalePrice9: 0,
        wholesalePrice10: 0,
        discountedPurchasePrice: 0,
        discountedPurchaseTax: 0,
        discountedPurchaseAmount: 0,
        discountedProfitMargin: 0,
        discountedSellingPrice: 0,
        discountedSellingTax: 0,
        discountedSellingAmount: 0,
        discountStartDate: '2000-01-01T00:00:00',
        discountEndDate: '2000-01-01T00:00:00',
        orderUnit: 'EA',
        pointApplication: 'True',
        pointScore: 0,
        memberPriceApplication: 'False',
        memberPrice: 0,
        memberTax: 0,
        memberAmount: 0,
        transactionStartDate: '2000-01-01T00:00:00',
        transactionEndDate: '2100-12-31T00:00:00',
        inBoxSellingAmount: 0,
        outBoxSellingAmount: 0,
        catonBoxSellingAmount: 0,
        modifiedDate: '2023-07-26T09:38:43',
        remarks: '',
        sellingPurchase: false,
        emptyBottleCode: '',
        productType: '주방조리',
        isDeleted: false,
        modifiedBy: '0099',
        createdBy: '0099',
        createdDate: '2023-07-26T09:38:43',
        taxName: 'Giao Hang',
        storeName: 'HYOJUNG2',
    },
    {
        barcode: 'D0067',
        productName: 'Bánh Trứng Miễn Phí',
        shortName: 'Bánh Trứng Miễn Phí',
        specification: '',
        unit: 'Cái',
        color: '',
        transactionType: '정상거래',
        taxCode: 'D10102',
        businessCode: '00001',
        inBoxQuantity: 0,
        outBoxQuantity: 0,
        catonBoxQuantity: 0,
        inBoxCode: '',
        outBoxCode: '',
        catonBoxCode: '',
        taxType: '8',
        purchasePrice: 0,
        purchaseTax: 0,
        purchaseAmount: 0,
        profitMargin: 100.0,
        sellingPrice: 0,
        sellingTax: 0,
        sellingAmount: 0,
        consumerPrice: 0,
        wholesalePrice1: 0,
        wholesalePrice2: 0,
        wholesalePrice3: 0,
        wholesalePrice4: 0,
        wholesalePrice5: 0,
        wholesalePrice6: 0,
        wholesalePrice7: 0,
        wholesalePrice8: 0,
        wholesalePrice9: 0,
        wholesalePrice10: 0,
        discountedPurchasePrice: 0,
        discountedPurchaseTax: 0,
        discountedPurchaseAmount: 0,
        discountedProfitMargin: 0,
        discountedSellingPrice: 0,
        discountedSellingTax: 0,
        discountedSellingAmount: 0,
        discountStartDate: '2000-01-01T00:00:00',
        discountEndDate: '2000-01-01T00:00:00',
        orderUnit: 'EA',
        pointApplication: 'False',
        pointScore: 0,
        memberPriceApplication: 'False',
        memberPrice: 0,
        memberTax: 0,
        memberAmount: 0,
        transactionStartDate: '2000-01-01T00:00:00',
        transactionEndDate: '2100-12-31T00:00:00',
        inBoxSellingAmount: 0,
        outBoxSellingAmount: 0,
        catonBoxSellingAmount: 0,
        modifiedDate: '2023-11-02T15:02:37',
        remarks: '',
        sellingPurchase: false,
        emptyBottleCode: '',
        productType: '주방조리',
        isDeleted: false,
        modifiedBy: '0099',
        createdBy: '0099',
        createdDate: '2023-11-02T15:02:37',
        taxName: 'Tax 10',
        storeName: 'HYOJUNG2',
    },
    {
        barcode: 'S023',
        productName: 'Bánh xèo hải sản (해물파전)',
        shortName: 'Bánh xèo hải sản (해물파전)',
        specification: '',
        unit: 'Suất',
        color: '',
        transactionType: '정상거래',
        taxCode: 'M10101',
        businessCode: '00001',
        inBoxQuantity: 0,
        outBoxQuantity: 0,
        catonBoxQuantity: 0,
        inBoxCode: '0',
        outBoxCode: '0',
        catonBoxCode: '0',
        taxType: '8',
        purchasePrice: 0,
        purchaseTax: 0,
        purchaseAmount: 0,
        profitMargin: 100.0,
        sellingPrice: 250000,
        sellingTax: 20000,
        sellingAmount: 270000,
        consumerPrice: 0,
        wholesalePrice1: 0,
        wholesalePrice2: 0,
        wholesalePrice3: 0,
        wholesalePrice4: 0,
        wholesalePrice5: 0,
        wholesalePrice6: 0,
        wholesalePrice7: 0,
        wholesalePrice8: 0,
        wholesalePrice9: 0,
        wholesalePrice10: 0,
        discountedPurchasePrice: 0,
        discountedPurchaseTax: 0,
        discountedPurchaseAmount: 0,
        discountedProfitMargin: 0,
        discountedSellingPrice: 0,
        discountedSellingTax: 0,
        discountedSellingAmount: 0,
        discountStartDate: '2000-01-01T00:00:00',
        discountEndDate: '2000-01-01T00:00:00',
        orderUnit: 'EA',
        pointApplication: 'True',
        pointScore: 0,
        memberPriceApplication: 'False',
        memberPrice: 0,
        memberTax: 0,
        memberAmount: 0,
        transactionStartDate: '2000-01-01T00:00:00',
        transactionEndDate: '2100-12-31T00:00:00',
        inBoxSellingAmount: 0,
        outBoxSellingAmount: 0,
        catonBoxSellingAmount: 0,
        modifiedDate: '2023-06-12T15:21:27',
        remarks: '',
        sellingPurchase: false,
        emptyBottleCode: '',
        productType: '주방조리',
        isDeleted: false,
        modifiedBy: '1111',
        createdBy: '1111',
        createdDate: '2021-07-17T02:38:39.037',
        taxName: 'Ruou,Bia',
        storeName: 'HYOJUNG2',
    },
    {
        barcode: 'D0013',
        productName: 'Bia',
        shortName: 'Bia',
        specification: '',
        unit: 'Chai',
        color: '',
        transactionType: '정상거래',
        taxCode: 'D10104',
        businessCode: '00001',
        inBoxQuantity: 0,
        outBoxQuantity: 0,
        catonBoxQuantity: 0,
        inBoxCode: '',
        outBoxCode: '',
        catonBoxCode: '',
        taxType: '10',
        purchasePrice: 0,
        purchaseTax: 0,
        purchaseAmount: 0,
        profitMargin: 100.0,
        sellingPrice: 40000,
        sellingTax: 4000,
        sellingAmount: 44000,
        consumerPrice: 0,
        wholesalePrice1: 0,
        wholesalePrice2: 0,
        wholesalePrice3: 0,
        wholesalePrice4: 0,
        wholesalePrice5: 0,
        wholesalePrice6: 0,
        wholesalePrice7: 0,
        wholesalePrice8: 0,
        wholesalePrice9: 0,
        wholesalePrice10: 0,
        discountedPurchasePrice: 0,
        discountedPurchaseTax: 0,
        discountedPurchaseAmount: 0,
        discountedProfitMargin: 0,
        discountedSellingPrice: 0,
        discountedSellingTax: 0,
        discountedSellingAmount: 0,
        discountStartDate: '2000-01-01T00:00:00',
        discountEndDate: '2000-01-01T00:00:00',
        orderUnit: 'EA',
        pointApplication: 'True',
        pointScore: 0,
        memberPriceApplication: 'False',
        memberPrice: 0,
        memberTax: 0,
        memberAmount: 0,
        transactionStartDate: '2000-01-01T00:00:00',
        transactionEndDate: '2100-12-31T00:00:00',
        inBoxSellingAmount: 0,
        outBoxSellingAmount: 0,
        catonBoxSellingAmount: 0,
        modifiedDate: '2023-07-06T23:18:42',
        remarks: '',
        sellingPurchase: false,
        emptyBottleCode: '',
        productType: '주방조리',
        isDeleted: false,
        modifiedBy: '0099',
        createdBy: '1111',
        createdDate: '2021-11-16T11:27:12',
        taxName: 'Ruou,Bia',
        storeName: 'HYOJUNG2',
    },
    {
        barcode: 'D0041',
        productName: 'Bia',
        shortName: 'Bia',
        specification: '',
        unit: 'Chai',
        color: '',
        transactionType: '정상거래',
        taxCode: 'D10104',
        businessCode: '00001',
        inBoxQuantity: 0,
        outBoxQuantity: 0,
        catonBoxQuantity: 0,
        inBoxCode: '',
        outBoxCode: '',
        catonBoxCode: '',
        taxType: '10',
        purchasePrice: 0,
        purchaseTax: 0,
        purchaseAmount: 0,
        profitMargin: 100.0,
        sellingPrice: 20000,
        sellingTax: 2000,
        sellingAmount: 22000,
        consumerPrice: 0,
        wholesalePrice1: 0,
        wholesalePrice2: 0,
        wholesalePrice3: 0,
        wholesalePrice4: 0,
        wholesalePrice5: 0,
        wholesalePrice6: 0,
        wholesalePrice7: 0,
        wholesalePrice8: 0,
        wholesalePrice9: 0,
        wholesalePrice10: 0,
        discountedPurchasePrice: 0,
        discountedPurchaseTax: 0,
        discountedPurchaseAmount: 0,
        discountedProfitMargin: 0,
        discountedSellingPrice: 0,
        discountedSellingTax: 0,
        discountedSellingAmount: 0,
        discountStartDate: '2000-01-01T00:00:00',
        discountEndDate: '2000-01-01T00:00:00',
        orderUnit: 'EA',
        pointApplication: 'False',
        pointScore: 0,
        memberPriceApplication: 'False',
        memberPrice: 0,
        memberTax: 0,
        memberAmount: 0,
        transactionStartDate: '2000-01-01T00:00:00',
        transactionEndDate: '2100-12-31T00:00:00',
        inBoxSellingAmount: 0,
        outBoxSellingAmount: 0,
        catonBoxSellingAmount: 0,
        modifiedDate: '2023-07-06T23:29:11',
        remarks: '',
        sellingPurchase: false,
        emptyBottleCode: '',
        productType: '주방조리',
        isDeleted: false,
        modifiedBy: '0099',
        createdBy: '0099',
        createdDate: '2022-01-29T20:30:05',
        taxName: 'Ruou,Bia',
        storeName: 'HYOJUNG2',
    },
    {
        barcode: 'D0045',
        productName: 'Bia Heineken',
        shortName: 'Bia Heineken',
        specification: '',
        unit: 'Chai',
        color: '',
        transactionType: '정상거래',
        taxCode: 'D10104',
        businessCode: '00001',
        inBoxQuantity: 0,
        outBoxQuantity: 0,
        catonBoxQuantity: 0,
        inBoxCode: '',
        outBoxCode: '',
        catonBoxCode: '',
        taxType: '10',
        purchasePrice: 0,
        purchaseTax: 0,
        purchaseAmount: 0,
        profitMargin: 100.0,
        sellingPrice: 50000,
        sellingTax: 5000,
        sellingAmount: 55000,
        consumerPrice: 0,
        wholesalePrice1: 0,
        wholesalePrice2: 0,
        wholesalePrice3: 0,
        wholesalePrice4: 0,
        wholesalePrice5: 0,
        wholesalePrice6: 0,
        wholesalePrice7: 0,
        wholesalePrice8: 0,
        wholesalePrice9: 0,
        wholesalePrice10: 0,
        discountedPurchasePrice: 0,
        discountedPurchaseTax: 0,
        discountedPurchaseAmount: 0,
        discountedProfitMargin: 0,
        discountedSellingPrice: 0,
        discountedSellingTax: 0,
        discountedSellingAmount: 0,
        discountStartDate: '2000-01-01T00:00:00',
        discountEndDate: '2000-01-01T00:00:00',
        orderUnit: 'EA',
        pointApplication: 'False',
        pointScore: 0,
        memberPriceApplication: 'False',
        memberPrice: 0,
        memberTax: 0,
        memberAmount: 0,
        transactionStartDate: '2000-01-01T00:00:00',
        transactionEndDate: '2100-12-31T00:00:00',
        inBoxSellingAmount: 0,
        outBoxSellingAmount: 0,
        catonBoxSellingAmount: 0,
        modifiedDate: '2023-07-06T23:30:42',
        remarks: '',
        sellingPurchase: false,
        emptyBottleCode: '',
        productType: '주방조리',
        isDeleted: false,
        modifiedBy: '0099',
        createdBy: '0099',
        createdDate: '2022-05-10T11:03:45',
        taxName: 'Ruou,Bia',
        storeName: 'HYOJUNG2',
    },
    {
        barcode: 'D0019',
        productName: 'Bia Heineken',
        shortName: 'Bia Heineken',
        specification: '',
        unit: 'Lon',
        color: '',
        transactionType: '정상거래',
        taxCode: 'D10104',
        businessCode: '00001',
        inBoxQuantity: 0,
        outBoxQuantity: 0,
        catonBoxQuantity: 0,
        inBoxCode: '',
        outBoxCode: '',
        catonBoxCode: '',
        taxType: '10',
        purchasePrice: 0,
        purchaseTax: 0,
        purchaseAmount: 0,
        profitMargin: 100.0,
        sellingPrice: 30000,
        sellingTax: 3000,
        sellingAmount: 33000,
        consumerPrice: 0,
        wholesalePrice1: 0,
        wholesalePrice2: 0,
        wholesalePrice3: 0,
        wholesalePrice4: 0,
        wholesalePrice5: 0,
        wholesalePrice6: 0,
        wholesalePrice7: 0,
        wholesalePrice8: 0,
        wholesalePrice9: 0,
        wholesalePrice10: 0,
        discountedPurchasePrice: 0,
        discountedPurchaseTax: 0,
        discountedPurchaseAmount: 0,
        discountedProfitMargin: 0,
        discountedSellingPrice: 0,
        discountedSellingTax: 0,
        discountedSellingAmount: 0,
        discountStartDate: '2000-01-01T00:00:00',
        discountEndDate: '2000-01-01T00:00:00',
        orderUnit: 'EA',
        pointApplication: 'True',
        pointScore: 0,
        memberPriceApplication: 'False',
        memberPrice: 0,
        memberTax: 0,
        memberAmount: 0,
        transactionStartDate: '2000-01-01T00:00:00',
        transactionEndDate: '2100-12-31T00:00:00',
        inBoxSellingAmount: 0,
        outBoxSellingAmount: 0,
        catonBoxSellingAmount: 0,
        modifiedDate: '2023-07-06T23:19:57',
        remarks: '',
        sellingPurchase: false,
        emptyBottleCode: '',
        productType: '주방조리',
        isDeleted: false,
        modifiedBy: '0099',
        createdBy: '0099',
        createdDate: '2021-11-19T12:29:00',
        taxName: 'Ruou,Bia',
        storeName: 'HYOJUNG2',
    },
    {
        barcode: 'D0040',
        productName: 'Bia Heineken',
        shortName: 'Bia Heineken',
        specification: '',
        unit: 'Lon',
        color: '',
        transactionType: '정상거래',
        taxCode: 'D10104',
        businessCode: '00001',
        inBoxQuantity: 0,
        outBoxQuantity: 0,
        catonBoxQuantity: 0,
        inBoxCode: '',
        outBoxCode: '',
        catonBoxCode: '',
        taxType: '10',
        purchasePrice: 0,
        purchaseTax: 0,
        purchaseAmount: 0,
        profitMargin: 100.0,
        sellingPrice: 40000,
        sellingTax: 4000,
        sellingAmount: 44000,
        consumerPrice: 0,
        wholesalePrice1: 0,
        wholesalePrice2: 0,
        wholesalePrice3: 0,
        wholesalePrice4: 0,
        wholesalePrice5: 0,
        wholesalePrice6: 0,
        wholesalePrice7: 0,
        wholesalePrice8: 0,
        wholesalePrice9: 0,
        wholesalePrice10: 0,
        discountedPurchasePrice: 0,
        discountedPurchaseTax: 0,
        discountedPurchaseAmount: 0,
        discountedProfitMargin: 0,
        discountedSellingPrice: 0,
        discountedSellingTax: 0,
        discountedSellingAmount: 0,
        discountStartDate: '2000-01-01T00:00:00',
        discountEndDate: '2000-01-01T00:00:00',
        orderUnit: 'EA',
        pointApplication: 'False',
        pointScore: 0,
        memberPriceApplication: 'False',
        memberPrice: 0,
        memberTax: 0,
        memberAmount: 0,
        transactionStartDate: '2000-01-01T00:00:00',
        transactionEndDate: '2100-12-31T00:00:00',
        inBoxSellingAmount: 0,
        outBoxSellingAmount: 0,
        catonBoxSellingAmount: 0,
        modifiedDate: '2023-07-06T23:28:34',
        remarks: '',
        sellingPurchase: false,
        emptyBottleCode: '',
        productType: '주방조리',
        isDeleted: false,
        modifiedBy: '0099',
        createdBy: '0099',
        createdDate: '2022-01-15T11:54:04',
        taxName: 'Ruou,Bia',
        storeName: 'HYOJUNG2',
    },
    {
        barcode: 'D0017',
        productName: 'Bia Sai Gon',
        shortName: 'Bia Sai Gon',
        specification: '',
        unit: 'Lon',
        color: '',
        transactionType: '정상거래',
        taxCode: 'D10104',
        businessCode: '00001',
        inBoxQuantity: 0,
        outBoxQuantity: 0,
        catonBoxQuantity: 0,
        inBoxCode: '',
        outBoxCode: '',
        catonBoxCode: '',
        taxType: '10',
        purchasePrice: 0,
        purchaseTax: 0,
        purchaseAmount: 0,
        profitMargin: 100.0,
        sellingPrice: 30000,
        sellingTax: 3000,
        sellingAmount: 33000,
        consumerPrice: 0,
        wholesalePrice1: 0,
        wholesalePrice2: 0,
        wholesalePrice3: 0,
        wholesalePrice4: 0,
        wholesalePrice5: 0,
        wholesalePrice6: 0,
        wholesalePrice7: 0,
        wholesalePrice8: 0,
        wholesalePrice9: 0,
        wholesalePrice10: 0,
        discountedPurchasePrice: 0,
        discountedPurchaseTax: 0,
        discountedPurchaseAmount: 0,
        discountedProfitMargin: 0,
        discountedSellingPrice: 0,
        discountedSellingTax: 0,
        discountedSellingAmount: 0,
        discountStartDate: '2000-01-01T00:00:00',
        discountEndDate: '2000-01-01T00:00:00',
        orderUnit: 'EA',
        pointApplication: 'True',
        pointScore: 0,
        memberPriceApplication: 'False',
        memberPrice: 0,
        memberTax: 0,
        memberAmount: 0,
        transactionStartDate: '2000-01-01T00:00:00',
        transactionEndDate: '2100-12-31T00:00:00',
        inBoxSellingAmount: 0,
        outBoxSellingAmount: 0,
        catonBoxSellingAmount: 0,
        modifiedDate: '2023-07-06T23:19:39',
        remarks: '',
        sellingPurchase: false,
        emptyBottleCode: '',
        productType: '주방조리',
        isDeleted: false,
        modifiedBy: '0099',
        createdBy: '0099',
        createdDate: '2021-11-19T12:25:16',
        taxName: 'Ruou,Bia',
        storeName: 'HYOJUNG2',
    },
    {
        barcode: 'D0018',
        productName: 'Bia Tiger',
        shortName: 'Bia Tiger',
        specification: '',
        unit: 'Lon',
        color: '',
        transactionType: '정상거래',
        taxCode: 'D10104',
        businessCode: '00001',
        inBoxQuantity: 0,
        outBoxQuantity: 0,
        catonBoxQuantity: 0,
        inBoxCode: '',
        outBoxCode: '',
        catonBoxCode: '',
        taxType: '10',
        purchasePrice: 0,
        purchaseTax: 0,
        purchaseAmount: 0,
        profitMargin: 100.0,
        sellingPrice: 35000,
        sellingTax: 3500,
        sellingAmount: 38500,
        consumerPrice: 0,
        wholesalePrice1: 0,
        wholesalePrice2: 0,
        wholesalePrice3: 0,
        wholesalePrice4: 0,
        wholesalePrice5: 0,
        wholesalePrice6: 0,
        wholesalePrice7: 0,
        wholesalePrice8: 0,
        wholesalePrice9: 0,
        wholesalePrice10: 0,
        discountedPurchasePrice: 0,
        discountedPurchaseTax: 0,
        discountedPurchaseAmount: 0,
        discountedProfitMargin: 0,
        discountedSellingPrice: 0,
        discountedSellingTax: 0,
        discountedSellingAmount: 0,
        discountStartDate: '2000-01-01T00:00:00',
        discountEndDate: '2000-01-01T00:00:00',
        orderUnit: 'EA',
        pointApplication: 'True',
        pointScore: 0,
        memberPriceApplication: 'False',
        memberPrice: 0,
        memberTax: 0,
        memberAmount: 0,
        transactionStartDate: '2000-01-01T00:00:00',
        transactionEndDate: '2100-12-31T00:00:00',
        inBoxSellingAmount: 0,
        outBoxSellingAmount: 0,
        catonBoxSellingAmount: 0,
        modifiedDate: '2023-07-06T23:19:47',
        remarks: '',
        sellingPurchase: false,
        emptyBottleCode: '',
        productType: '주방조리',
        isDeleted: false,
        modifiedBy: '0099',
        createdBy: '0099',
        createdDate: '2021-11-19T12:28:05',
        taxName: 'Ruou,Bia',
        storeName: 'HYOJUNG2',
    },
    {
        barcode: 'D0044',
        productName: 'Bia Tiger',
        shortName: 'Bia Tiger',
        specification: '',
        unit: 'Lon',
        color: '',
        transactionType: '정상거래',
        taxCode: 'D10104',
        businessCode: '00001',
        inBoxQuantity: 0,
        outBoxQuantity: 0,
        catonBoxQuantity: 0,
        inBoxCode: '',
        outBoxCode: '',
        catonBoxCode: '',
        taxType: '10',
        purchasePrice: 0,
        purchaseTax: 0,
        purchaseAmount: 0,
        profitMargin: 100.0,
        sellingPrice: 45000,
        sellingTax: 4500,
        sellingAmount: 49500,
        consumerPrice: 0,
        wholesalePrice1: 0,
        wholesalePrice2: 0,
        wholesalePrice3: 0,
        wholesalePrice4: 0,
        wholesalePrice5: 0,
        wholesalePrice6: 0,
        wholesalePrice7: 0,
        wholesalePrice8: 0,
        wholesalePrice9: 0,
        wholesalePrice10: 0,
        discountedPurchasePrice: 0,
        discountedPurchaseTax: 0,
        discountedPurchaseAmount: 0,
        discountedProfitMargin: 0,
        discountedSellingPrice: 0,
        discountedSellingTax: 0,
        discountedSellingAmount: 0,
        discountStartDate: '2000-01-01T00:00:00',
        discountEndDate: '2000-01-01T00:00:00',
        orderUnit: 'EA',
        pointApplication: 'False',
        pointScore: 0,
        memberPriceApplication: 'False',
        memberPrice: 0,
        memberTax: 0,
        memberAmount: 0,
        transactionStartDate: '2000-01-01T00:00:00',
        transactionEndDate: '2100-12-31T00:00:00',
        inBoxSellingAmount: 0,
        outBoxSellingAmount: 0,
        catonBoxSellingAmount: 0,
        modifiedDate: '2023-07-06T23:30:10',
        remarks: '',
        sellingPurchase: false,
        emptyBottleCode: '',
        productType: '주방조리',
        isDeleted: false,
        modifiedBy: '0099',
        createdBy: '0099',
        createdDate: '2022-05-10T11:02:43',
        taxName: 'Ruou,Bia',
        storeName: 'HYOJUNG2',
    },
    {
        barcode: 'D0038',
        productName: 'Bia Tiger',
        shortName: 'Bia Tiger',
        specification: '',
        unit: 'Lon',
        color: '',
        transactionType: '정상거래',
        taxCode: 'D10104',
        businessCode: '00001',
        inBoxQuantity: 0,
        outBoxQuantity: 0,
        catonBoxQuantity: 0,
        inBoxCode: '',
        outBoxCode: '',
        catonBoxCode: '',
        taxType: '10',
        purchasePrice: 0,
        purchaseTax: 0,
        purchaseAmount: 0,
        profitMargin: 100.0,
        sellingPrice: 35000,
        sellingTax: 3500,
        sellingAmount: 38500,
        consumerPrice: 0,
        wholesalePrice1: 0,
        wholesalePrice2: 0,
        wholesalePrice3: 0,
        wholesalePrice4: 0,
        wholesalePrice5: 0,
        wholesalePrice6: 0,
        wholesalePrice7: 0,
        wholesalePrice8: 0,
        wholesalePrice9: 0,
        wholesalePrice10: 0,
        discountedPurchasePrice: 0,
        discountedPurchaseTax: 0,
        discountedPurchaseAmount: 0,
        discountedProfitMargin: 0,
        discountedSellingPrice: 0,
        discountedSellingTax: 0,
        discountedSellingAmount: 0,
        discountStartDate: '2000-01-01T00:00:00',
        discountEndDate: '2000-01-01T00:00:00',
        orderUnit: 'EA',
        pointApplication: 'False',
        pointScore: 0,
        memberPriceApplication: 'False',
        memberPrice: 0,
        memberTax: 0,
        memberAmount: 0,
        transactionStartDate: '2000-01-01T00:00:00',
        transactionEndDate: '2100-12-31T00:00:00',
        inBoxSellingAmount: 0,
        outBoxSellingAmount: 0,
        catonBoxSellingAmount: 0,
        modifiedDate: '2023-07-06T23:28:21',
        remarks: '',
        sellingPurchase: false,
        emptyBottleCode: '',
        productType: '주방조리',
        isDeleted: false,
        modifiedBy: '0099',
        createdBy: '0099',
        createdDate: '2022-01-15T11:53:10',
        taxName: 'Ruou,Bia',
        storeName: 'HYOJUNG2',
    },
    {
        barcode: 'S014',
        productName: 'Bia tiger (타이거맥주)',
        shortName: 'Bia tiger (타이거맥주)',
        specification: '',
        unit: 'Lon',
        color: '',
        transactionType: '정상거래',
        taxCode: 'M10101',
        businessCode: '00001',
        inBoxQuantity: 0,
        outBoxQuantity: 0,
        catonBoxQuantity: 0,
        inBoxCode: '0',
        outBoxCode: '0',
        catonBoxCode: '0',
        taxType: '10',
        purchasePrice: 0,
        purchaseTax: 0,
        purchaseAmount: 0,
        profitMargin: 100.0,
        sellingPrice: 60000,
        sellingTax: 6000,
        sellingAmount: 66000,
        consumerPrice: 0,
        wholesalePrice1: 0,
        wholesalePrice2: 0,
        wholesalePrice3: 0,
        wholesalePrice4: 0,
        wholesalePrice5: 0,
        wholesalePrice6: 0,
        wholesalePrice7: 0,
        wholesalePrice8: 0,
        wholesalePrice9: 0,
        wholesalePrice10: 0,
        discountedPurchasePrice: 0,
        discountedPurchaseTax: 0,
        discountedPurchaseAmount: 0,
        discountedProfitMargin: 0,
        discountedSellingPrice: 0,
        discountedSellingTax: 0,
        discountedSellingAmount: 0,
        discountStartDate: '2000-01-01T00:00:00',
        discountEndDate: '2000-01-01T00:00:00',
        orderUnit: 'EA',
        pointApplication: 'True',
        pointScore: 0,
        memberPriceApplication: 'False',
        memberPrice: 0,
        memberTax: 0,
        memberAmount: 0,
        transactionStartDate: '2000-01-01T00:00:00',
        transactionEndDate: '2100-12-31T00:00:00',
        inBoxSellingAmount: 0,
        outBoxSellingAmount: 0,
        catonBoxSellingAmount: 0,
        modifiedDate: '2022-05-10T15:47:40.02',
        remarks: '',
        sellingPurchase: false,
        emptyBottleCode: '',
        productType: '주방조리',
        isDeleted: false,
        modifiedBy: '1111',
        createdBy: '1111',
        createdDate: '2021-07-17T01:38:39.02',
        taxName: 'Ruou,Bia',
        storeName: 'HYOJUNG2',
    },
    {
        barcode: '18806427000918',
        productName: 'Box A',
        shortName: 'Box A',
        specification: '',
        unit: 'Hop',
        color: '',
        transactionType: '정상거래',
        taxCode: 'D10102',
        businessCode: '00001',
        inBoxQuantity: 0,
        outBoxQuantity: 0,
        catonBoxQuantity: 0,
        inBoxCode: '',
        outBoxCode: '',
        catonBoxCode: '',
        taxType: '10',
        purchasePrice: 320000,
        purchaseTax: 0,
        purchaseAmount: 320000,
        profitMargin: 15.79,
        sellingPrice: 380000,
        sellingTax: 0,
        sellingAmount: 380000,
        consumerPrice: 0,
        wholesalePrice1: 0,
        wholesalePrice2: 0,
        wholesalePrice3: 0,
        wholesalePrice4: 0,
        wholesalePrice5: 0,
        wholesalePrice6: 0,
        wholesalePrice7: 0,
        wholesalePrice8: 0,
        wholesalePrice9: 0,
        wholesalePrice10: 0,
        discountedPurchasePrice: 0,
        discountedPurchaseTax: 0,
        discountedPurchaseAmount: 0,
        discountedProfitMargin: 0,
        discountedSellingPrice: 0,
        discountedSellingTax: 0,
        discountedSellingAmount: 0,
        discountStartDate: '2000-01-01T00:00:00',
        discountEndDate: '2000-01-01T00:00:00',
        orderUnit: 'EA',
        pointApplication: 'False',
        pointScore: 0,
        memberPriceApplication: 'False',
        memberPrice: 0,
        memberTax: 0,
        memberAmount: 0,
        transactionStartDate: '2000-01-01T00:00:00',
        transactionEndDate: '2100-12-31T00:00:00',
        inBoxSellingAmount: 0,
        outBoxSellingAmount: 0,
        catonBoxSellingAmount: 0,
        modifiedDate: '2025-01-17T11:49:55',
        remarks: '',
        sellingPurchase: false,
        emptyBottleCode: '',
        productType: '일반상품',
        isDeleted: false,
        modifiedBy: '1111',
        createdBy: '1111',
        createdDate: '2025-01-17T11:49:55',
        taxName: 'Tax 10',
        storeName: 'HYOJUNG2',
    },
    {
        barcode: 'D0078',
        productName: 'BUFFET 1 người (< 3 nguoi)',
        shortName: 'BUFFET 1 người (Nhom < 3 nguoi)',
        specification: '',
        unit: 'Suất',
        color: '',
        transactionType: '정상거래',
        taxCode: 'D10101',
        businessCode: '00001',
        inBoxQuantity: 0,
        outBoxQuantity: 0,
        catonBoxQuantity: 0,
        inBoxCode: '',
        outBoxCode: '',
        catonBoxCode: '',
        taxType: '8',
        purchasePrice: 0,
        purchaseTax: 0,
        purchaseAmount: 0,
        profitMargin: 100.0,
        sellingPrice: 129000,
        sellingTax: 10320,
        sellingAmount: 139320,
        consumerPrice: 0,
        wholesalePrice1: 0,
        wholesalePrice2: 0,
        wholesalePrice3: 0,
        wholesalePrice4: 0,
        wholesalePrice5: 0,
        wholesalePrice6: 0,
        wholesalePrice7: 0,
        wholesalePrice8: 0,
        wholesalePrice9: 0,
        wholesalePrice10: 0,
        discountedPurchasePrice: 0,
        discountedPurchaseTax: 0,
        discountedPurchaseAmount: 0,
        discountedProfitMargin: 0,
        discountedSellingPrice: 0,
        discountedSellingTax: 0,
        discountedSellingAmount: 0,
        discountStartDate: '2000-01-01T00:00:00',
        discountEndDate: '2000-01-01T00:00:00',
        orderUnit: 'EA',
        pointApplication: 'False',
        pointScore: 0,
        memberPriceApplication: 'False',
        memberPrice: 0,
        memberTax: 0,
        memberAmount: 0,
        transactionStartDate: '2000-01-01T00:00:00',
        transactionEndDate: '2100-12-31T00:00:00',
        inBoxSellingAmount: 0,
        outBoxSellingAmount: 0,
        catonBoxSellingAmount: 0,
        modifiedDate: '2024-07-29T11:59:49',
        remarks: '',
        sellingPurchase: false,
        emptyBottleCode: '',
        productType: '주방조리',
        isDeleted: false,
        modifiedBy: '0099',
        createdBy: '0099',
        createdDate: '2024-07-29T11:59:49',
        taxName: 'Tax 8',
        storeName: 'HYOJUNG2',
    },
    {
        barcode: 'D0079',
        productName: 'BUFFET 1 người (4 nguoi)',
        shortName: 'BUFFET 1 người (4 nguoi)',
        specification: '',
        unit: 'Suất',
        color: '',
        transactionType: '정상거래',
        taxCode: 'D10101',
        businessCode: '00001',
        inBoxQuantity: 0,
        outBoxQuantity: 0,
        catonBoxQuantity: 0,
        inBoxCode: '',
        outBoxCode: '',
        catonBoxCode: '',
        taxType: '8',
        purchasePrice: 0,
        purchaseTax: 0,
        purchaseAmount: 0,
        profitMargin: 100.0,
        sellingPrice: 119000,
        sellingTax: 9520,
        sellingAmount: 128520,
        consumerPrice: 0,
        wholesalePrice1: 0,
        wholesalePrice2: 0,
        wholesalePrice3: 0,
        wholesalePrice4: 0,
        wholesalePrice5: 0,
        wholesalePrice6: 0,
        wholesalePrice7: 0,
        wholesalePrice8: 0,
        wholesalePrice9: 0,
        wholesalePrice10: 0,
        discountedPurchasePrice: 0,
        discountedPurchaseTax: 0,
        discountedPurchaseAmount: 0,
        discountedProfitMargin: 0,
        discountedSellingPrice: 0,
        discountedSellingTax: 0,
        discountedSellingAmount: 0,
        discountStartDate: '2000-01-01T00:00:00',
        discountEndDate: '2000-01-01T00:00:00',
        orderUnit: 'EA',
        pointApplication: 'False',
        pointScore: 0,
        memberPriceApplication: 'False',
        memberPrice: 0,
        memberTax: 0,
        memberAmount: 0,
        transactionStartDate: '2000-01-01T00:00:00',
        transactionEndDate: '2100-12-31T00:00:00',
        inBoxSellingAmount: 0,
        outBoxSellingAmount: 0,
        catonBoxSellingAmount: 0,
        modifiedDate: '2024-07-29T12:00:49',
        remarks: '',
        sellingPurchase: false,
        emptyBottleCode: '',
        productType: '주방조리',
        isDeleted: false,
        modifiedBy: '0099',
        createdBy: '0099',
        createdDate: '2024-07-29T12:00:49',
        taxName: 'Tax 8',
        storeName: 'HYOJUNG2',
    },
    {
        barcode: 'D0076',
        productName: 'BUFFET 1 người (Nhom < 3 nguoi)',
        shortName: 'BUFFET 1 người (Nhom < 3 nguoi)',
        specification: '',
        unit: 'Suất',
        color: '',
        transactionType: '정상거래',
        taxCode: 'D10101',
        businessCode: '00001',
        inBoxQuantity: 0,
        outBoxQuantity: 0,
        catonBoxQuantity: 0,
        inBoxCode: '',
        outBoxCode: '',
        catonBoxCode: '',
        taxType: '8',
        purchasePrice: 0,
        purchaseTax: 0,
        purchaseAmount: 0,
        profitMargin: 100.0,
        sellingPrice: 129000,
        sellingTax: 10320,
        sellingAmount: 139320,
        consumerPrice: 0,
        wholesalePrice1: 0,
        wholesalePrice2: 0,
        wholesalePrice3: 0,
        wholesalePrice4: 0,
        wholesalePrice5: 0,
        wholesalePrice6: 0,
        wholesalePrice7: 0,
        wholesalePrice8: 0,
        wholesalePrice9: 0,
        wholesalePrice10: 0,
        discountedPurchasePrice: 0,
        discountedPurchaseTax: 0,
        discountedPurchaseAmount: 0,
        discountedProfitMargin: 0,
        discountedSellingPrice: 0,
        discountedSellingTax: 0,
        discountedSellingAmount: 0,
        discountStartDate: '2000-01-01T00:00:00',
        discountEndDate: '2000-01-01T00:00:00',
        orderUnit: 'EA',
        pointApplication: 'False',
        pointScore: 0,
        memberPriceApplication: 'False',
        memberPrice: 0,
        memberTax: 0,
        memberAmount: 0,
        transactionStartDate: '2000-01-01T00:00:00',
        transactionEndDate: '2100-12-31T00:00:00',
        inBoxSellingAmount: 0,
        outBoxSellingAmount: 0,
        catonBoxSellingAmount: 0,
        modifiedDate: '2024-07-29T11:20:10',
        remarks: '',
        sellingPurchase: false,
        emptyBottleCode: '',
        productType: '일반상품',
        isDeleted: false,
        modifiedBy: '0099',
        createdBy: '0099',
        createdDate: '2024-07-29T11:20:10',
        taxName: 'Tax 8',
        storeName: 'HYOJUNG2',
    },
    {
        barcode: 'D0077',
        productName: 'BUFFET 1 người (Nhom > 4 nguoi)',
        shortName: 'BUFFET 1 người (Nhom > 4 nguoi)',
        specification: '',
        unit: 'Suất',
        color: '',
        transactionType: '정상거래',
        taxCode: 'D10101',
        businessCode: '00001',
        inBoxQuantity: 0,
        outBoxQuantity: 0,
        catonBoxQuantity: 0,
        inBoxCode: '',
        outBoxCode: '',
        catonBoxCode: '',
        taxType: '8',
        purchasePrice: 0,
        purchaseTax: 0,
        purchaseAmount: 0,
        profitMargin: 100.0,
        sellingPrice: 119000,
        sellingTax: 9520,
        sellingAmount: 128520,
        consumerPrice: 0,
        wholesalePrice1: 0,
        wholesalePrice2: 0,
        wholesalePrice3: 0,
        wholesalePrice4: 0,
        wholesalePrice5: 0,
        wholesalePrice6: 0,
        wholesalePrice7: 0,
        wholesalePrice8: 0,
        wholesalePrice9: 0,
        wholesalePrice10: 0,
        discountedPurchasePrice: 0,
        discountedPurchaseTax: 0,
        discountedPurchaseAmount: 0,
        discountedProfitMargin: 0,
        discountedSellingPrice: 0,
        discountedSellingTax: 0,
        discountedSellingAmount: 0,
        discountStartDate: '2000-01-01T00:00:00',
        discountEndDate: '2000-01-01T00:00:00',
        orderUnit: 'EA',
        pointApplication: 'False',
        pointScore: 0,
        memberPriceApplication: 'False',
        memberPrice: 0,
        memberTax: 0,
        memberAmount: 0,
        transactionStartDate: '2000-01-01T00:00:00',
        transactionEndDate: '2100-12-31T00:00:00',
        inBoxSellingAmount: 0,
        outBoxSellingAmount: 0,
        catonBoxSellingAmount: 0,
        modifiedDate: '2024-07-29T11:21:19',
        remarks: '',
        sellingPurchase: false,
        emptyBottleCode: '',
        productType: '일반상품',
        isDeleted: false,
        modifiedBy: '0099',
        createdBy: '0099',
        createdDate: '2024-07-29T11:21:19',
        taxName: 'Tax 8',
        storeName: 'HYOJUNG2',
    },
    {
        barcode: 'D0001',
        productName: 'Buffet Người Lớn',
        shortName: 'Nguoi Lon 일반',
        specification: '',
        unit: 'Suất',
        color: '',
        transactionType: '정상거래',
        taxCode: 'D10101',
        businessCode: '00001',
        inBoxQuantity: 0,
        outBoxQuantity: 0,
        catonBoxQuantity: 0,
        inBoxCode: '',
        outBoxCode: '',
        catonBoxCode: '',
        taxType: '8',
        purchasePrice: 0,
        purchaseTax: 0,
        purchaseAmount: 0,
        profitMargin: 100.0,
        sellingPrice: 139000,
        sellingTax: 11120,
        sellingAmount: 150120,
        consumerPrice: 0,
        wholesalePrice1: 0,
        wholesalePrice2: 0,
        wholesalePrice3: 0,
        wholesalePrice4: 0,
        wholesalePrice5: 0,
        wholesalePrice6: 0,
        wholesalePrice7: 0,
        wholesalePrice8: 0,
        wholesalePrice9: 0,
        wholesalePrice10: 0,
        discountedPurchasePrice: 0,
        discountedPurchaseTax: 0,
        discountedPurchaseAmount: 0,
        discountedProfitMargin: 0,
        discountedSellingPrice: 0,
        discountedSellingTax: 0,
        discountedSellingAmount: 0,
        discountStartDate: '2000-01-01T00:00:00',
        discountEndDate: '2000-01-01T00:00:00',
        orderUnit: 'EA',
        pointApplication: 'True',
        pointScore: 0,
        memberPriceApplication: 'False',
        memberPrice: 0,
        memberTax: 0,
        memberAmount: 0,
        transactionStartDate: '2000-01-01T00:00:00',
        transactionEndDate: '2100-12-31T00:00:00',
        inBoxSellingAmount: 0,
        outBoxSellingAmount: 0,
        catonBoxSellingAmount: 0,
        modifiedDate: '2023-07-06T23:15:28',
        remarks: '',
        sellingPurchase: false,
        emptyBottleCode: '',
        productType: '주방조리',
        isDeleted: false,
        modifiedBy: '0099',
        createdBy: '1111',
        createdDate: '2021-10-27T11:57:06',
        taxName: 'Tax 8',
        storeName: 'HYOJUNG2',
    },
    {
        barcode: 'VL101',
        productName: 'BUFFET NGƯỜI LỚN',
        shortName: 'BUFFET NGƯỜI LỚN',
        specification: '',
        unit: 'SUẤT',
        color: '',
        transactionType: '정상거래',
        taxCode: 'D10101',
        businessCode: '00001',
        inBoxQuantity: 0,
        outBoxQuantity: 0,
        catonBoxQuantity: 0,
        inBoxCode: '',
        outBoxCode: '',
        catonBoxCode: '',
        taxType: '8',
        purchasePrice: 0,
        purchaseTax: 0,
        purchaseAmount: 0,
        profitMargin: 100.0,
        sellingPrice: 200000,
        sellingTax: 16000,
        sellingAmount: 216000,
        consumerPrice: 0,
        wholesalePrice1: 0,
        wholesalePrice2: 0,
        wholesalePrice3: 0,
        wholesalePrice4: 0,
        wholesalePrice5: 0,
        wholesalePrice6: 0,
        wholesalePrice7: 0,
        wholesalePrice8: 0,
        wholesalePrice9: 0,
        wholesalePrice10: 0,
        discountedPurchasePrice: 0,
        discountedPurchaseTax: 0,
        discountedPurchaseAmount: 0,
        discountedProfitMargin: 0,
        discountedSellingPrice: 0,
        discountedSellingTax: 0,
        discountedSellingAmount: 0,
        discountStartDate: '2000-01-01T00:00:00',
        discountEndDate: '2000-01-01T00:00:00',
        orderUnit: 'EA',
        pointApplication: 'False',
        pointScore: 0,
        memberPriceApplication: 'False',
        memberPrice: 0,
        memberTax: 0,
        memberAmount: 0,
        transactionStartDate: '2000-01-01T00:00:00',
        transactionEndDate: '2100-12-31T00:00:00',
        inBoxSellingAmount: 0,
        outBoxSellingAmount: 0,
        catonBoxSellingAmount: 0,
        modifiedDate: '2024-08-27T11:25:51',
        remarks: '',
        sellingPurchase: false,
        emptyBottleCode: '',
        productType: '주방조리',
        isDeleted: false,
        modifiedBy: '1111',
        createdBy: '1111',
        createdDate: '2024-08-27T11:25:51',
        taxName: 'Tax 8',
        storeName: 'HYOJUNG2',
    },
    {
        barcode: 'D0075',
        productName: 'BUFFET NGUOI LON (4 PAX)',
        shortName: 'BUFFET NGUOI LON (4 PAX)',
        specification: '',
        unit: 'Suất',
        color: '',
        transactionType: '정상거래',
        taxCode: 'D10101',
        businessCode: '00001',
        inBoxQuantity: 0,
        outBoxQuantity: 0,
        catonBoxQuantity: 0,
        inBoxCode: '',
        outBoxCode: '',
        catonBoxCode: '',
        taxType: '8',
        purchasePrice: 0,
        purchaseTax: 0,
        purchaseAmount: 0,
        profitMargin: 100.0,
        sellingPrice: 417000,
        sellingTax: 33360,
        sellingAmount: 450360,
        consumerPrice: 0,
        wholesalePrice1: 0,
        wholesalePrice2: 0,
        wholesalePrice3: 0,
        wholesalePrice4: 0,
        wholesalePrice5: 0,
        wholesalePrice6: 0,
        wholesalePrice7: 0,
        wholesalePrice8: 0,
        wholesalePrice9: 0,
        wholesalePrice10: 0,
        discountedPurchasePrice: 0,
        discountedPurchaseTax: 0,
        discountedPurchaseAmount: 0,
        discountedProfitMargin: 0,
        discountedSellingPrice: 0,
        discountedSellingTax: 0,
        discountedSellingAmount: 0,
        discountStartDate: '2000-01-01T00:00:00',
        discountEndDate: '2000-01-01T00:00:00',
        orderUnit: 'EA',
        pointApplication: 'False',
        pointScore: 0,
        memberPriceApplication: 'False',
        memberPrice: 0,
        memberTax: 0,
        memberAmount: 0,
        transactionStartDate: '2000-01-01T00:00:00',
        transactionEndDate: '2100-12-31T00:00:00',
        inBoxSellingAmount: 0,
        outBoxSellingAmount: 0,
        catonBoxSellingAmount: 0,
        modifiedDate: '2024-07-29T10:57:50',
        remarks: '',
        sellingPurchase: false,
        emptyBottleCode: '',
        productType: '일반상품',
        isDeleted: false,
        modifiedBy: '0099',
        createdBy: '0099',
        createdDate: '2024-07-29T10:57:50',
        taxName: 'Tax 8',
        storeName: 'HYOJUNG2',
    },
    {
        barcode: 'D0072',
        productName: 'BUFFET NGƯỜI LỚN (4 pax)',
        shortName: 'BUFFET NGƯỜI LỚN (4 pax)',
        specification: '',
        unit: 'Suất',
        color: '',
        transactionType: '정상거래',
        taxCode: 'D10101',
        businessCode: '00001',
        inBoxQuantity: 0,
        outBoxQuantity: 0,
        catonBoxQuantity: 0,
        inBoxCode: '',
        outBoxCode: '',
        catonBoxCode: '',
        taxType: '8',
        purchasePrice: 0,
        purchaseTax: 0,
        purchaseAmount: 0,
        profitMargin: 100.0,
        sellingPrice: 417000,
        sellingTax: 33360,
        sellingAmount: 450360,
        consumerPrice: 0,
        wholesalePrice1: 0,
        wholesalePrice2: 0,
        wholesalePrice3: 0,
        wholesalePrice4: 0,
        wholesalePrice5: 0,
        wholesalePrice6: 0,
        wholesalePrice7: 0,
        wholesalePrice8: 0,
        wholesalePrice9: 0,
        wholesalePrice10: 0,
        discountedPurchasePrice: 0,
        discountedPurchaseTax: 0,
        discountedPurchaseAmount: 0,
        discountedProfitMargin: 0,
        discountedSellingPrice: 0,
        discountedSellingTax: 0,
        discountedSellingAmount: 0,
        discountStartDate: '2000-01-01T00:00:00',
        discountEndDate: '2000-01-01T00:00:00',
        orderUnit: 'EA',
        pointApplication: 'False',
        pointScore: 0,
        memberPriceApplication: 'False',
        memberPrice: 0,
        memberTax: 0,
        memberAmount: 0,
        transactionStartDate: '2000-01-01T00:00:00',
        transactionEndDate: '2100-12-31T00:00:00',
        inBoxSellingAmount: 0,
        outBoxSellingAmount: 0,
        catonBoxSellingAmount: 0,
        modifiedDate: '2024-04-27T11:07:03',
        remarks: '',
        sellingPurchase: false,
        emptyBottleCode: '',
        productType: '주방조리',
        isDeleted: false,
        modifiedBy: '0099',
        createdBy: '0099',
        createdDate: '2024-04-27T11:01:26',
        taxName: 'Tax 8',
        storeName: 'HYOJUNG2',
    },
];
