export const storeListFake = [
    {
        key: '0',
        StoreCode: '00001',
        StoreType: 'Retail',
        TransactionType: 'Cash',
        Name: 'Cửa hàng A',
        Representative: 'Nguyễn Văn A',
        RepresentativeId: 'REP01',
        PhoneNumber: '0123456789',
        FaxNumber: '0987654321',
        Email: 'exampleA@mail.com',
        Homepage: 'http://storeA.com',
        TotalArea: 150,
        StoreArea: 100,
        ParkingSpaces: 20,
        EmployeeCount: 5,
        BankName: 'Ngân hàng A',
        AccountNumber: '123456789',
        AccountHolder: 'Nguyễn Văn A',
        TransactionStartDate: new Date('2023-01-01'),
        TransactionEndDate: new Date('2024-01-01'),
        BusinessNumber1: '123',
        BusinessNumber2: '45',
        BusinessNumber3: '67890',
        PostalCode: '100000',
        Address: 'Địa chỉ A',
        DetailedAddress: 'Chi tiết địa chỉ A',
        BusinessType: 'Bán lẻ',
        BusinessCategory: 'Thời trang',
        DisplayOrder: 1,
        TransactionLevel: 1,
        BrandId: 'BRAND01',
        BrandName: 'Thương hiệu A',
        ViettelId: 'ViettelA',
        ViettelPassword: 'passwordA',
        TemplateCode: 'TEMP01',
        InvoiceSeries: 'INV001',
    },
    {
        key: '1',
        StoreCode: '00002',
        StoreType: 'Wholesale',
        TransactionType: 'Credit',
        Name: 'Cửa hàng B',
        Representative: 'Trần Văn B',
        RepresentativeId: 'REP02',
        PhoneNumber: '0123456788',
        FaxNumber: '0987654320',
        Email: 'exampleB@mail.com',
        Homepage: 'http://storeB.com',
        TotalArea: 200,
        StoreArea: 150,
        ParkingSpaces: 30,
        EmployeeCount: 10,
        BankName: 'Ngân hàng B',
        AccountNumber: '987654321',
        AccountHolder: 'Trần Văn B',
        TransactionStartDate: new Date('2023-02-01'),
        TransactionEndDate: new Date('2024-02-01'),
        BusinessNumber1: '987',
        BusinessNumber2: '65',
        BusinessNumber3: '43210',
        PostalCode: '200000',
        Address: 'Địa chỉ B',
        DetailedAddress: 'Chi tiết địa chỉ B',
        BusinessType: 'Bán buôn',
        BusinessCategory: 'Điện máy',
        DisplayOrder: 2,
        TransactionLevel: 2,
        BrandId: 'BRAND02',
        BrandName: 'Thương hiệu B',
        ViettelId: 'ViettelB',
        ViettelPassword: 'passwordB',
        TemplateCode: 'TEMP02',
        InvoiceSeries: 'INV002',
    },
    {
        key: '2',
        StoreCode: '00003',
        StoreType: 'Franchise',
        TransactionType: 'Cash',
        Name: 'Cửa hàng C',
        Representative: 'Lê Văn C',
        RepresentativeId: 'REP03',
        PhoneNumber: '0123456787',
        FaxNumber: '0987654319',
        Email: 'exampleC@mail.com',
        Homepage: 'http://storeC.com',
        TotalArea: 180,
        StoreArea: 120,
        ParkingSpaces: 25,
        EmployeeCount: 8,
        BankName: 'Ngân hàng C',
        AccountNumber: '456789123',
        AccountHolder: 'Lê Văn C',
        TransactionStartDate: new Date('2023-03-01'),
        TransactionEndDate: new Date('2024-03-01'),
        BusinessNumber1: '456',
        BusinessNumber2: '78',
        BusinessNumber3: '12345',
        PostalCode: '300000',
        Address: 'Địa chỉ C',
        DetailedAddress: 'Chi tiết địa chỉ C',
        BusinessType: 'Nhượng quyền',
        BusinessCategory: 'Thực phẩm',
        DisplayOrder: 3,
        TransactionLevel: 3,
        BrandId: 'BRAND03',
        BrandName: 'Thương hiệu C',
        ViettelId: 'ViettelC',
        ViettelPassword: 'passwordC',
        TemplateCode: 'TEMP03',
        InvoiceSeries: 'INV003',
    },
    {
        key: '3',
        StoreCode: '00004',
        StoreType: 'Online',
        TransactionType: 'Credit',
        Name: 'Cửa hàng D',
        Representative: 'Phạm Văn D',
        RepresentativeId: 'REP04',
        PhoneNumber: '0123456786',
        FaxNumber: '0987654318',
        Email: 'exampleD@mail.com',
        Homepage: 'http://storeD.com',
        TotalArea: 120,
        StoreArea: 80,
        ParkingSpaces: 15,
        EmployeeCount: 3,
        BankName: 'Ngân hàng D',
        AccountNumber: '321654987',
        AccountHolder: 'Phạm Văn D',
        TransactionStartDate: new Date('2023-04-01'),
        TransactionEndDate: new Date('2024-04-01'),
        BusinessNumber1: '321',
        BusinessNumber2: '65',
        BusinessNumber3: '98765',
        PostalCode: '400000',
        Address: 'Địa chỉ D',
        DetailedAddress: 'Chi tiết địa chỉ D',
        BusinessType: 'Bán hàng trực tuyến',
        BusinessCategory: 'Sách',
        DisplayOrder: 4,
        TransactionLevel: 1,
        BrandId: 'BRAND04',
        BrandName: 'Thương hiệu D',
        ViettelId: 'ViettelD',
        ViettelPassword: 'passwordD',
        TemplateCode: 'TEMP04',
        InvoiceSeries: 'INV004',
    },
    {
        key: '4',
        StoreCode: '00005',
        StoreType: 'Retail',
        TransactionType: 'Cash',
        Name: 'Cửa hàng E',
        Representative: 'Nguyễn Thị E',
        RepresentativeId: 'REP05',
        PhoneNumber: '0123456785',
        FaxNumber: '0987654317',
        Email: 'exampleE@mail.com',
        Homepage: 'http://storeE.com',
        TotalArea: 160,
        StoreArea: 110,
        ParkingSpaces: 22,
        EmployeeCount: 6,
        BankName: 'Ngân hàng E',
        AccountNumber: '654789321',
        AccountHolder: 'Nguyễn Thị E',
        TransactionStartDate: new Date('2023-05-01'),
        TransactionEndDate: new Date('2024-05-01'),
        BusinessNumber1: '654',
        BusinessNumber2: '32',
        BusinessNumber3: '54321',
        PostalCode: '500000',
        Address: 'Địa chỉ E',
        DetailedAddress: 'Chi tiết địa chỉ E',
        BusinessType: 'Bán lẻ',
        BusinessCategory: 'Điện thoại',
        DisplayOrder: 5,
        TransactionLevel: 2,
        BrandId: 'BRAND05',
        BrandName: 'Thương hiệu E',
        ViettelId: 'ViettelE',
        ViettelPassword: 'passwordE',
        TemplateCode: 'TEMP05',
        InvoiceSeries: 'INV005',
    },
    {
        key: '5',
        StoreCode: '00006',
        StoreType: 'Wholesale',
        TransactionType: 'Credit',
        Name: 'Cửa hàng F',
        Representative: 'Trần Thị F',
        RepresentativeId: 'REP06',
        PhoneNumber: '0123456784',
        FaxNumber: '0987654316',
        Email: 'exampleF@mail.com',
        Homepage: 'http://storeF.com',
        TotalArea: 190,
        StoreArea: 140,
        ParkingSpaces: 28,
        EmployeeCount: 9,
        BankName: 'Ngân hàng F',
        AccountNumber: '789123456',
        AccountHolder: 'Trần Thị F',
        TransactionStartDate: new Date('2023-06-01'),
        TransactionEndDate: new Date('2024-06-01'),
        BusinessNumber1: '789',
        BusinessNumber2: '12',
        BusinessNumber3: '34567',
        PostalCode: '600000',
        Address: 'Địa chỉ F',
        DetailedAddress: 'Chi tiết địa chỉ F',
        BusinessType: 'Bán buôn',
        BusinessCategory: 'Thời trang',
        DisplayOrder: 6,
        TransactionLevel: 3,
        BrandId: 'BRAND06',
        BrandName: 'Thương hiệu F',
        ViettelId: 'ViettelF',
        ViettelPassword: 'passwordF',
        TemplateCode: 'TEMP06',
        InvoiceSeries: 'INV006',
    },
    {
        key: '6',
        StoreCode: '00007',
        StoreType: 'Franchise',
        TransactionType: 'Cash',
        Name: 'Cửa hàng G',
        Representative: 'Lê Văn G',
        RepresentativeId: 'REP07',
        PhoneNumber: '0123456783',
        FaxNumber: '0987654315',
        Email: 'exampleG@mail.com',
        Homepage: 'http://storeG.com',
        TotalArea: 170,
        StoreArea: 130,
        ParkingSpaces: 18,
        EmployeeCount: 7,
        BankName: 'Ngân hàng G',
        AccountNumber: '321321321',
        AccountHolder: 'Lê Văn G',
        TransactionStartDate: new Date('2023-07-01'),
        TransactionEndDate: new Date('2024-07-01'),
        BusinessNumber1: '321',
        BusinessNumber2: '21',
        BusinessNumber3: '12345',
        PostalCode: '700000',
        Address: 'Địa chỉ G',
        DetailedAddress: 'Chi tiết địa chỉ G',
        BusinessType: 'Nhượng quyền',
        BusinessCategory: 'Thực phẩm',
        DisplayOrder: 7,
        TransactionLevel: 1,
        BrandId: 'BRAND07',
        BrandName: 'Thương hiệu G',
        ViettelId: 'ViettelG',
        ViettelPassword: 'passwordG',
        TemplateCode: 'TEMP07',
        InvoiceSeries: 'INV007',
    },
    {
        key: '7',
        StoreCode: '00008',
        StoreType: 'Online',
        TransactionType: 'Credit',
        Name: 'Cửa hàng H',
        Representative: 'Nguyễn Văn H',
        RepresentativeId: 'REP08',
        PhoneNumber: '0123456782',
        FaxNumber: '0987654314',
        Email: 'exampleH@mail.com',
        Homepage: 'http://storeH.com',
        TotalArea: 130,
        StoreArea: 90,
        ParkingSpaces: 12,
        EmployeeCount: 4,
        BankName: 'Ngân hàng H',
        AccountNumber: '654654654',
        AccountHolder: 'Nguyễn Văn H',
        TransactionStartDate: new Date('2023-08-01'),
        TransactionEndDate: new Date('2024-08-01'),
        BusinessNumber1: '654',
        BusinessNumber2: '12',
        BusinessNumber3: '98765',
        PostalCode: '800000',
        Address: 'Địa chỉ H',
        DetailedAddress: 'Chi tiết địa chỉ H',
        BusinessType: 'Bán hàng trực tuyến',
        BusinessCategory: 'Sách',
        DisplayOrder: 8,
        TransactionLevel: 2,
        BrandId: 'BRAND08',
        BrandName: 'Thương hiệu H',
        ViettelId: 'ViettelH',
        ViettelPassword: 'passwordH',
        TemplateCode: 'TEMP08',
        InvoiceSeries: 'INV008',
    },
    {
        key: '8',
        StoreCode: '00009',
        StoreType: 'Retail',
        TransactionType: 'Cash',
        Name: 'Cửa hàng I',
        Representative: 'Trần Văn I',
        RepresentativeId: 'REP09',
        PhoneNumber: '0123456781',
        FaxNumber: '0987654313',
        Email: 'exampleI@mail.com',
        Homepage: 'http://storeI.com',
        TotalArea: 140,
        StoreArea: 100,
        ParkingSpaces: 20,
        EmployeeCount: 5,
        BankName: 'Ngân hàng I',
        AccountNumber: '789789789',
        AccountHolder: 'Trần Văn I',
        TransactionStartDate: new Date('2023-09-01'),
        TransactionEndDate: new Date('2024-09-01'),
        BusinessNumber1: '789',
        BusinessNumber2: '78',
        BusinessNumber3: '23456',
        PostalCode: '900000',
        Address: 'Địa chỉ I',
        DetailedAddress: 'Chi tiết địa chỉ I',
        BusinessType: 'Bán lẻ',
        BusinessCategory: 'Điện tử',
        DisplayOrder: 9,
        TransactionLevel: 3,
        BrandId: 'BRAND09',
        BrandName: 'Thương hiệu I',
        ViettelId: 'ViettelI',
        ViettelPassword: 'passwordI',
        TemplateCode: 'TEMP09',
        InvoiceSeries: 'INV009',
    },
    {
        key: '10',
        StoreCode: '00010',
        StoreType: 'Wholesale',
        TransactionType: 'Credit',
        Name: 'Cửa hàng J',
        Representative: 'Nguyễn Thị J',
        RepresentativeId: 'REP10',
        PhoneNumber: '0123456780',
        FaxNumber: '0987654312',
        Email: 'exampleJ@mail.com',
        Homepage: 'http://storeJ.com',
        TotalArea: 210,
        StoreArea: 160,
        ParkingSpaces: 35,
        EmployeeCount: 12,
        BankName: 'Ngân hàng J',
        AccountNumber: '321987654',
        AccountHolder: 'Nguyễn Thị J',
        TransactionStartDate: new Date('2023-10-01'),
        TransactionEndDate: new Date('2024-10-01'),
        BusinessNumber1: '321',
        BusinessNumber2: '98',
        BusinessNumber3: '12345',
        PostalCode: '1000000',
        Address: 'Địa chỉ J',
        DetailedAddress: 'Chi tiết địa chỉ J',
        BusinessType: 'Bán buôn',
        BusinessCategory: 'Thực phẩm',
        DisplayOrder: 10,
        TransactionLevel: 1,
        BrandId: 'BRAND10',
        BrandName: 'Thương hiệu J',
        ViettelId: 'ViettelJ',
        ViettelPassword: 'passwordJ',
        TemplateCode: 'TEMP10',
        InvoiceSeries: 'INV010',
    },
];
