import StoreOperations from './Store/StoreOperations';
import StoreDetailSettings from './Store/StoreDetailSettings';
import CashDrawer2 from './Store/CashDrawer2';
import TAX from './Store/TAX';
import OperationsManagement from './Store/OperationsManagement';
import OrderPosCancelFunctionOption from './Store/OrderPosCancelFunctionOption';
import PrinterLanguageSetting from './Store/PrinterLanguageSetting';
import AutoClosePopupOption from './Store/AutoClosePopupOption';
import PosInformation from './Pos/PosInformation';
import PrinterSetting from './Pos/PrinterSetting';
import LabelPrintSetting from './Pos/LabelPrintSetting';
import GuestPager from './Pos/GuestPager';
import PosDisplaySetting from './Pos/PosDisplaySetting';
import CidDevice from './Pos/CidDevice';
import PrintOptionByPos from './Pos/PrintOptionByPos';
import WindowsKioksOption from './Pos/WindowsKioksOption';
import MsrSetting from './Pos/MsrSetting';
import MsrPortSetting from './Pos/MsrPortSetting';
import EcrSetting from './Pos/EcrSetting';
import StoreInfoTaxReceipt from './OptionSetting/StoreInfoTaxReceipt';
import SettingQRCode from './OptionSetting/SettingQRCode';
import ShowAdditionalDataInEodPrintout from './OptionSetting/ShowAdditionalDataInEodPrintout';
import OneTouchOption from './OptionSetting/OneTouchOption';
import BarcodeUnregisterdItemOption from './OptionSetting/BarcodeUnregisterdItemOption';
import CallerIdentificationReceiveAction from './OptionSetting/CallerIdentificationReceiveAction';
import CashDrawerOpenOption from './OptionSetting/CashDrawerOpenOption';
import ClearTableSetting from './OptionSetting/ClearTableSetting';
import EnterNumberOfCustomerSetting from './OptionSetting/EnterNumberOfCustomerSetting';
import SelectEmployeeSetting from './OptionSetting/SelectEmployeeSetting';
import DiscountOrderOption from './OptionSetting/DiscountOrderOption';
import ShowItemBarcodeOption from './OptionSetting/ShowItemBarcodeOption';
import RebateIssue from './OptionSetting/RebateIssue';
import WeightBarcodeOption from './OptionSetting/WeightBarcodeOption';
import TenderMethod from './OptionSetting/TenderMethod';
import CashDrawerOpenTiming from './OptionSetting/CashDrawerOpenTiming';
import PrepaymentFunctionButtonSetting from './OptionSetting/PrepaymentFunctionButtonSetting';
import PrepaidOrderRetentionOptions from './OptionSetting/PrepaidOrderRetentionOptions';
import DeliverySettings from './OptionSetting/DeliverySettings';
import DeliveryOrder from './OptionSetting/DeliveryOrder';
import ChangeWeightControl from './OptionSetting/ChangeWeightControl';
import DiscountOption from './OptionSetting/DiscountOption';
import PaymentOptionsImmediately from './OptionSetting/PaymentOptionsImmediately';
import NoticePopupOption from './OptionSetting/NoticePopupOption';
import SetAllCancellationType from './OptionSetting/SetAllCancellationType';
import CurrencyChangeOption from './OptionSetting/CurrencyChangeOption';
import EnableKeepUnitChange from './OptionSetting/EnableKeepUnitChange';
import Receipt from './PrintOptions/Receipt';
import CustomerOrderPrint from './PrintOptions/CustomerOrderPrint';
import KitchenOrderPrint from './PrintOptions/KitchenOrderPrint';
import WaitingListTag from './PrintOptions/WaitingListTag';

export { default } from './Settings';
export { StoreOperations, StoreDetailSettings, CashDrawer2, TAX, OperationsManagement, OrderPosCancelFunctionOption };
export { PrinterLanguageSetting, AutoClosePopupOption, PosInformation, PrinterSetting, LabelPrintSetting, GuestPager };
export { PosDisplaySetting, CidDevice, PrintOptionByPos, WindowsKioksOption, MsrSetting, MsrPortSetting, EcrSetting };
export { StoreInfoTaxReceipt, SettingQRCode, ShowAdditionalDataInEodPrintout, OneTouchOption, RebateIssue };
export { BarcodeUnregisterdItemOption, CallerIdentificationReceiveAction, CashDrawerOpenOption, ClearTableSetting };
export { EnterNumberOfCustomerSetting, SelectEmployeeSetting, DiscountOrderOption, ShowItemBarcodeOption };
export { WeightBarcodeOption, TenderMethod, CashDrawerOpenTiming, PrepaymentFunctionButtonSetting };
export { PrepaidOrderRetentionOptions, DeliverySettings, DeliveryOrder, ChangeWeightControl, DiscountOption };
export { PaymentOptionsImmediately, NoticePopupOption, SetAllCancellationType, CurrencyChangeOption };
export { EnableKeepUnitChange, Receipt, CustomerOrderPrint, KitchenOrderPrint, WaitingListTag };
