import StoreOperations from './Store/StoreOperations';
import StoreDetailSettings from './Store/StoreDetailSettings';
import CashDrawer2 from './Store/CashDrawer2';
import TAX from './Store/TAX';
import OperationsManagement from './Store/OperationsManagement';
import OrderPosCancelFunctionOption from './Store/OrderPosCancelFunctionOption';
import PrinterLanguageSetting from './Store/PrinterLanguageSetting';
import AutoClosePopupOption from './Store/AutoClosePopupOption';
import PosInformation from './Pos/PosInformation';
import PrinterSetting from './Pos/PrinterSetting';
import LabelPrintSetting from './Pos/LabelPrintSetting';
import GuestPager from './Pos/GuestPager';
import PosDisplaySetting from './Pos/PosDisplaySetting';
import CidDevice from './Pos/CidDevice';
import PrintOptionByPos from './Pos/PrintOptionByPos';
import WindowsKioksOption from './Pos/WindowsKioksOption';
import MsrSetting from './Pos/MsrSetting';
import MsrPortSetting from './Pos/MsrPortSetting';
import EcrSetting from './Pos/EcrSetting';
import StoreInfoTaxReceipt from './OptionSetting/StoreInfoTaxReceipt';
import SettingQRCode from './OptionSetting/SettingQRCode';
import ShowAdditionalDataInEodPrintout from './OptionSetting/ShowAdditionalDataInEodPrintout';
import OneTouchOption from './OptionSetting/OneTouchOption';
import BarcodeUnregisterdItemOption from './OptionSetting/BarcodeUnregisterdItemOption';
import CallerIdentificationReceiveAction from './OptionSetting/CallerIdentificationReceiveAction';
import CashDrawerOpenOption from './OptionSetting/CashDrawerOpenOption';
import ClearTableSetting from './OptionSetting/ClearTableSetting';
import EnterNumberOfCustomerSetting from './OptionSetting/EnterNumberOfCustomerSetting';
import SelectEmployeeSetting from './OptionSetting/SelectEmployeeSetting';
import DiscountOrderOption from './OptionSetting/DiscountOrderOption';
import ShowItemBarcodeOption from './OptionSetting/ShowItemBarcodeOption';

export { default } from './Settings';
export { StoreOperations, StoreDetailSettings, CashDrawer2, TAX, OperationsManagement, OrderPosCancelFunctionOption };
export { PrinterLanguageSetting, AutoClosePopupOption, PosInformation, PrinterSetting, LabelPrintSetting, GuestPager };
export { PosDisplaySetting, CidDevice, PrintOptionByPos, WindowsKioksOption, MsrSetting, MsrPortSetting, EcrSetting };
export { StoreInfoTaxReceipt, SettingQRCode, ShowAdditionalDataInEodPrintout, OneTouchOption };
export { BarcodeUnregisterdItemOption, CallerIdentificationReceiveAction, CashDrawerOpenOption, ClearTableSetting };
export { EnterNumberOfCustomerSetting, SelectEmployeeSetting, DiscountOrderOption, ShowItemBarcodeOption };
