const nameMap = {
    itemLevel1: {
        BASICSETTINGS: { pathKey: 'BasicSettings', Visiblename: 'Basic Settings' },
        MANAGERFUNCTION: { pathKey: 'ManagerFunction', Visiblename: 'Manager Function' },
        CUSTOMER: { pathKey: 'Customer', Visiblename: 'Customer' },
        OPERATIONREPORTS: { pathKey: 'OperationReports', Visiblename: 'Operation Reports' },
        SALEREPORTS: { pathKey: 'SaleReports', Visiblename: 'Sale Reports' },
        PURCHASEORDER: { pathKey: 'PurchaseOrder', Visiblename: 'Purchase Order' },
        SETTINGS: { pathKey: 'Settings', Visiblename: 'Settings' },
        BIZSMS: { pathKey: 'BIZSMS', Visiblename: 'BIZ SMS' },
        WEBLOGIN: { pathKey: 'WebLogin', Visiblename: 'Web Login' },
    },
    itemLevel2: {
        STOREMANAGEMENT: { pathKey: '#0', Visiblename: 'Store Management' },
        EMPLOYEEMANAGEMENT: { pathKey: '#1', Visiblename: 'Employee Management' },
        MENUMANAGEMENT: { pathKey: '#2', Visiblename: 'Menu Management' },
        POSSCREENLAYOUT: { pathKey: '#3', Visiblename: 'POS Screen Layout' },
        SALEREPORTS: { pathKey: '#0', Visiblename: 'Sale Reports' },
        SALESANALYSIS: { pathKey: '#1', Visiblename: 'Sales Analysis' },
        VOIDRETURN: { pathKey: '#2', Visiblename: 'POS Screen Layout' },
        DISCOUNTSTATUS: { pathKey: '#3', Visiblename: 'POS Screen Layout' },
        TAX: { pathKey: '#4', Visiblename: 'TAX' },
        EODREPORT: { pathKey: '#5', Visiblename: 'EOD Report' },
        INVENTORY: { pathKey: '#0', Visiblename: 'Inventory' },
        ACCOUNTING: { pathKey: '#1', Visiblename: 'Accounting' },
        SUPPLIER: { pathKey: '#2', Visiblename: 'Supplier' },
        STORE: { pathKey: '#3', Visiblename: 'Store' },
        POS: { pathKey: '#3', Visiblename: 'POS' },
        OPTIONSETTING: { pathKey: '#3', Visiblename: 'Option setting' },
        PRINTOPTIONS: { pathKey: '#3', Visiblename: 'Print Options' },
        SECURITY: { pathKey: '#3', Visiblename: 'Security' },
        NETWORKSERVER: { pathKey: '#3', Visiblename: 'Network Server' },
    },
    itemLevel3: {
        GROUPMANAGEMENT: { pathKey: 'GroupManagement', Visiblename: 'Group Management', parent: 'STOREMANAGEMENT' },
        STOREINFO: { pathKey: 'StoreInfo', Visiblename: 'Store Info', parent: 'STOREMANAGEMENT' },
        STORELIST: { pathKey: 'StoreList', Visiblename: 'Store List', parent: 'STOREMANAGEMENT' },
        WAREHOUSEMANAGEMENT: { pathKey: 'WarehouseManagement', Visiblename: 'Warehouse Management', parent: 'STOREMANAGEMENT' },
        CASHDRAWER: { pathKey: 'CashDrawer', Visiblename: 'Cash Drawer', parent: 'STOREMANAGEMENT' },
        DISCOUNT: { pathKey: 'Discount', Visiblename: 'Discount', parent: 'STOREMANAGEMENT' },
        EMPLOYEEGROUP: { pathKey: 'EmployeeGroup', Visiblename: 'Employee Group', parent: 'EMPLOYEEMANAGEMENT' },
        EMPLOYEEINFO: { pathKey: 'EmployeeInfo', Visiblename: 'Employee Info', parent: 'EMPLOYEEMANAGEMENT' },
        EMPLOYEELIST: { pathKey: 'EmployeeList', Visiblename: 'Employee List', parent: 'EMPLOYEEMANAGEMENT' },
        MENUSETUP: { pathKey: 'MenuSetup', Visiblename: 'Menu Setup', parent: 'MENUMANAGEMENT' },
        ITEMRECEIPTMANAGEMENT: { pathKey: 'ItemReceiptManagement', Visiblename: 'Item Receipt Management', parent: 'MENUMANAGEMENT' },
        ITEMRECEIPTMANAGER: { pathKey: 'ItemReceiptManager', Visiblename: 'Item Receipt Manager', parent: 'MENUMANAGEMENT' },
        TOPPINGSETTINGS: { pathKey: 'ToppingSettings', Visiblename: 'Topping Settings', parent: 'MENUMANAGEMENT' },
        SUBMENU: { pathKey: 'SubMenu', Visiblename: 'Sub Menu', parent: 'MENUMANAGEMENT' },
        MENUSEARCH: { pathKey: 'MenuSearch', Visiblename: 'Menu Search', parent: 'MENUMANAGEMENT' },
        INVENTORYITEMSEARCH: { pathKey: 'InventoryItemSearch', Visiblename: 'Inventory Item Search', parent: 'MENUMANAGEMENT' },
        MENUBOARDMANAGEMENT: { pathKey: 'MenuBoardManagement', Visiblename: 'Menu-Board Management', parent: 'MENUMANAGEMENT' },
        POSMENUBOARD: { pathKey: 'POSMenuBoard', Visiblename: 'POS Menu-Board', parent: 'MENUMANAGEMENT' },
        CATEGORYMANAGER: { pathKey: 'CategoryManager', Visiblename: 'Category Manager', parent: 'MENUMANAGEMENT' },
        RECIPEBUILDER: { pathKey: 'RecipeBuilder', Visiblename: 'Recipe Builder', parent: 'MENUMANAGEMENT' },
        RECIPESEARCH: { pathKey: 'RecipeSearch', Visiblename: 'Recipe Search', parent: 'MENUMANAGEMENT' },
        KITCHENMEMO: { pathKey: 'KitchenMemo', Visiblename: 'Kitchen Memo', parent: 'MENUMANAGEMENT' },
        ITEMMANAGEMENTBYSTRORE: { pathKey: 'ItemManagementByStrore', Visiblename: 'Item Management By Strore', parent: 'MENUMANAGEMENT' },
        CHANGEOFMULTILINGUALNAME: { pathKey: 'ChangeOfMultilingualName', Visiblename: 'Change of multilingual name', parent: 'MENUMANAGEMENT' },
        ITEMLINKEDCODEMANAGEMENT: { pathKey: 'ItemLinkedCodeManagement', Visiblename: 'Item linked code management', parent: 'MENUMANAGEMENT' },
        DAILYSALESREPORT: { pathKey: 'DailySalesReport', Visiblename: 'Daily Sales Report', parent: 'SALEREPORTS' },
        DAILYSALESSUMMARY: { pathKey: 'DailySalesSummary', Visiblename: 'Daily Sales Summary', parent: 'SALEREPORTS' },
        SALESSUMMARY: { pathKey: 'SalesSummary', Visiblename: 'Sales Summary', parent: 'SALEREPORTS' },
        DETAILEDSALESLIST: { pathKey: 'DetailedSalesList', Visiblename: 'Detailed Sales List', parent: 'SALEREPORTS' },
        SALESBYRECEIPT: { pathKey: 'SalesByReceipt', Visiblename: 'Sales By Receipt', parent: 'SALEREPORTS' },
        SALESBYRECEIPTDETAIL: { pathKey: 'SalesByReceiptDetail', Visiblename: 'Sales By Receipt Detail', parent: 'SALEREPORTS' },
        CASHRECEIPTAPPROVALCANCELATIONREPORT: { pathKey: 'CashReceiptApprovalCancelationReport', Visiblename: 'CashReceipt Approval/Cancelation Report', parent: 'SALEREPORTS' },
        CREDITCARDAPPROVALCANCELATIONREPORT: { pathKey: 'CreditCardApprovalCancelationReport', Visiblename: 'CreditCard Approval/Cancelation Report', parent: 'SALEREPORTS' },
        SALESREPORTBYCARDTYPEDETAIL: { pathKey: 'SalesReportByCardTypeDetail', Visiblename: 'Sales Report by Card Type Detail', parent: 'SALEREPORTS' },
        SALESRECORDBYEMPLOYEE: { pathKey: 'SalesRecordByEmployee', Visiblename: 'Sales Record by Employee', parent: 'SALEREPORTS' },
        SALESRECORDBYEMPLOYEEDATE: { pathKey: 'SalesRecordByEmployeeDate', Visiblename: 'Sales Record by Employee Date', parent: 'SALEREPORTS' },
        EMPLOYEECOMMISSION: { pathKey: 'EmployeeCommission', Visiblename: 'Employee Commission', parent: 'SALEREPORTS' },
        TOTALSALESREPORT: { pathKey: 'TotalSalesReport', Visiblename: 'Total Sales Report', parent: 'SALESANALYSIS' },
        SIMPLIFIEDSALESTOTAL: { pathKey: 'SimplifiedSalesTotal', Visiblename: 'Simplified Sales Total', parent: 'SALESANALYSIS' },
        AGGREGATEREVENUEITEMSBYCATEGORY: { pathKey: 'AggregateRevenueItemsByCategory', Visiblename: 'Aggregate revenue items by category', parent: 'SALESANALYSIS' },
        HOURLYSALES: { pathKey: 'HourlySales', Visiblename: 'Hourly Sales', parent: 'SALESANALYSIS' },
        TIMEOFDAYSALESREPORT: { pathKey: 'TimeOfDaySalesReport', Visiblename: 'Time of Day Sales Report', parent: 'SALESANALYSIS' },
        SALESREPORTBYPAYMENTTYPE: { pathKey: 'SalesReportByPaymentType', Visiblename: 'Sales Report by Payment Type', parent: 'SALESANALYSIS' },
        SALESREPORTBYCARDTYPE: { pathKey: 'SalesReportByCardType', Visiblename: 'Sales Report by Card Type', parent: 'SALESANALYSIS' },
        SALESRANKING: { pathKey: 'SalesRanking', Visiblename: 'Sales Ranking', parent: 'SALESANALYSIS' },
        SALESANALYSISREPORTITEM: { pathKey: 'SalesAnalysisReportItem', Visiblename: 'Sales Analysis Report(Item)', parent: 'SALESANALYSIS' },
        EMPLOYEESALESANALYSIS: { pathKey: 'EmployeeSalesAnalysis', Visiblename: 'Employee Sales Analysis', parent: 'SALESANALYSIS' },
        ORDERCANCELATIONREPORT: { pathKey: 'OrderCancelationReport', Visiblename: 'Order Cancelation Report', parent: 'VOIDRETURN' },
        VOIDSUMMARY: { pathKey: 'VoidSummary', Visiblename: 'Void Summary', parent: 'VOIDRETURN' },
        VOIDDETAIL: { pathKey: 'VoidDetail', Visiblename: 'Void Detail', parent: 'VOIDRETURN' },
        SALES_DISCOUNT_REPORT: { pathKey: 'SalesDiscountReport', Visiblename: 'Sales Discount Report', parent: 'DISCOUNTSTATUS' },
        SALES_DISCOUNT_SUMMARY: { pathKey: 'SalesDiscountSummary', Visiblename: 'Sales Discount Summary', parent: 'DISCOUNTSTATUS' },
        NO_TAX_SALE_REPORT: { pathKey: 'NoTaxSaleReport', Visiblename: 'No Tax Sale Report', parent: 'TAX' },
        TAX_DETAIL: { pathKey: 'TaxDetail', Visiblename: 'Tax Detail', parent: 'TAX' },
        TAX_SUMMARY: { pathKey: 'TaxSummary', Visiblename: 'Tax Summary', parent: 'TAX' },
        SALES_CASH_IN_OUT: { pathKey: 'SalesCashInOut', Visiblename: 'Sales Cash In Out', parent: 'EODREPORT' },
        CASH_IN_OUT: { pathKey: 'CashInOut', Visiblename: 'Cash In/Out', parent: 'EODREPORT' },
        INVENTORY_LOOK_UP: { pathKey: 'InventoryLookUp', Visiblename: 'Inventory Look Up', parent: 'INVENTORY' },
        INVENTORY_ADJUSTMENTS: { pathKey: 'InventoryAdjustments', Visiblename: 'Inventory Adjustments', parent: 'INVENTORY' },
        INVENTORY_TRANSFER: { pathKey: 'InventoryTransfer', Visiblename: 'Inventory Transfer', parent: 'INVENTORY' },
        IV_MANAGEMENT_TABLE: { pathKey: 'IVManagementTable', Visiblename: 'IV Management Table', parent: 'INVENTORY' },
        CUSTOMER_PURCHASE: { pathKey: 'CustomerPurchase', Visiblename: 'Customer Purchase', parent: 'ACCOUNTING' },
        CUSTOMER_SALE_B: { pathKey: 'CustomerSaleB', Visiblename: 'Customer Sale β', parent: 'ACCOUNTING' },
        SUPPLIER_LEDGER: { pathKey: 'SupplierLedger', Visiblename: 'Supplier Ledger', parent: 'ACCOUNTING' },
        CUSTOMER_LEDGER: { pathKey: 'CustomerLedger', Visiblename: 'Customer Ledger', parent: 'ACCOUNTING' },
        PAYABLE_REPORT: { pathKey: 'PayableReport', Visiblename: 'Payable Report', parent: 'ACCOUNTING' },
        RECEIVABLE_REPORT: { pathKey: 'ReceivableReport', Visiblename: 'Receivable Report', parent: 'ACCOUNTING' },
        SUPPLIER_SETTING: { pathKey: 'SupplierSetting', Visiblename: 'Supplier Setting', parent: 'SUPPLIER' },
        AMOUNT: { pathKey: 'Amount', Visiblename: 'Amount', parent: 'SUPPLIER' },
        STORE_OPERATIONS: { pathKey: 'StoreOperations', Visiblename: 'Store Operations', parent: 'STORE' },
        STORE_DETAIL_SETTING: { pathKey: 'StoreDetailSetting', Visiblename: 'Store Detail Setting', parent: 'STORE' },
        CASH_DRAWER: { pathKey: 'CashDrawer', Visiblename: 'Cash Drawer', parent: 'STORE' },
        TAX: { pathKey: 'Tax', Visiblename: 'Tax', parent: 'STORE' },
        OPERATIONS_MANAGEMENT: { pathKey: 'OperationsManagement', Visiblename: 'Operations Management', parent: 'STORE' },
        ORDER_POS_CANCEL_FUNCTION_OPTION: { pathKey: 'OrderPOSCancelFunctionOption', Visiblename: 'Order POS Cancel Function Option', parent: 'STORE' },
        PRINTER_LANGUAGE_SETTING: { pathKey: 'PrinterLanguageSetting', Visiblename: 'Printer Language Setting', parent: 'STORE' },
        AUTO_CLOSE_POPUP_OPTION: { pathKey: 'AutoClosePopupOption', Visiblename: 'Auto Close Popup Option', parent: 'STORE' },
        POS_INFORMATION: { pathKey: 'POSInformation', Visiblename: 'POS Information', parent: 'POS' },
        PRINTER_SETTING: { pathKey: 'PrinterSetting', Visiblename: 'Printer Setting', parent: 'POS' },
        LABEL_PRINT_SETTING: { pathKey: 'LabelPrintSetting', Visiblename: 'Label Print Setting', parent: 'POS' },
        GUEST_PAGER: { pathKey: 'GuestPager', Visiblename: 'Guest Pager', parent: 'POS' },
        POS_DISPLAY_SETTING: { pathKey: 'PosDisplaySetting', Visiblename: 'Pos Display Setting', parent: 'POS' },
        CID_DEVICE: { pathKey: 'CIDDevice', Visiblename: 'CID Device', parent: 'POS' },
        PRINT_OPTION_BY_POS: { pathKey: 'PrintOptionByPos', Visiblename: 'Print Option By Pos', parent: 'POS' },
        WINDOWS_KIOSK_OPTIONS: { pathKey: 'WindowsKioskOptions', Visiblename: 'Windows Kiosk Options', parent: 'POS' },
        MSR_SETTING: { pathKey: 'MSRSetting', Visiblename: 'MSR Setting', parent: 'POS' },
        MSR_PORT_SETTING: { pathKey: 'MSRPortSetting', Visiblename: 'MSR Port Setting', parent: 'POS' },
        ECR_SETTING: { pathKey: 'ECRSetting', Visiblename: 'ECR Setting', parent: 'POS' },
        STOREINFO_TAX_RECEIPT: { pathKey: 'StoreInfoTaxReceipt', Visiblename: 'StoreInfo(TAX Receipt)', parent: 'OPTIONSETTING' },
        SETTING_QR_CODE: { pathKey: 'SettingQRCode', Visiblename: 'Setting QR code', parent: 'OPTIONSETTING' },
        SHOW_ADDITIONAL_DATA_IN_EOD_PRINTOUT: { pathKey: 'ShowAdditionalDataInEODPrintout', Visiblename: 'Show additional data in EOD printout', parent: 'OPTIONSETTING' },
        ONE_TOUCH_OPTION: { pathKey: 'OneTouchOption', Visiblename: 'One Touch Option', parent: 'OPTIONSETTING' },
        BARCODE_UNREGISTERED_ITEM_OPTION: { pathKey: 'BarcodeUnregisteredItemOption', Visiblename: 'Barcode Unregisterd Item Option', parent: 'OPTIONSETTING' },
        CALLER_IDENTIFICATION_RECEIVE_ACTION: { pathKey: 'CallerIdentificationReceiveAction', Visiblename: 'Caller identification Receive Action', parent: 'OPTIONSETTING' },
        CASH_DRAWER_OPEN_OPTION: { pathKey: 'CashDrawerOpenOption', Visiblename: 'Cash drawer open option', parent: 'OPTIONSETTING' },
        CLEAR_TABLE_SETTING: { pathKey: 'ClearTableSetting', Visiblename: 'Clear Table Setting', parent: 'OPTIONSETTING' },
        ENTER_NUMBER_OF_CUSTOMER_SETTING: { pathKey: 'EnterNumberOfCustomerSetting', Visiblename: 'Enter number of customer Setting', parent: 'OPTIONSETTING' },
        SELECT_EMPLOYEE_SETTING: { pathKey: 'SelectEmployeeSetting', Visiblename: 'Select Employee Setting', parent: 'OPTIONSETTING' },
        DISCOUNT_ORDER_OPTION: { pathKey: 'DiscountOrderOption', Visiblename: 'Discount Order Option', parent: 'OPTIONSETTING' },
        SHOW_ITEM_BARCODE_OPTION: { pathKey: 'ShowItemBarcodeOption', Visiblename: 'Show item barcode option', parent: 'OPTIONSETTING' },
        REBATE_ISSUE: { pathKey: 'RebateIssue', Visiblename: 'Rebate Issue', parent: 'OPTIONSETTING' },
        WEIGHT_BARCODE_OPTION: { pathKey: 'WeightBarcodeOption', Visiblename: 'Weight Barcode Option', parent: 'OPTIONSETTING' },
        TENDER_METHOD_WHEN_MAKING_REFUND_RECEIPT: { pathKey: 'TenderMethodWhenMakingRefundReceipt', Visiblename: 'Tender method when making refund receipt', parent: 'OPTIONSETTING' },
        CASH_DRAWER_OPEN_TIMING: { pathKey: 'CashDrawerOpenTiming', Visiblename: 'Cash drawer open timing', parent: 'OPTIONSETTING' },
        PREPAYMENT_FUNCTION_BUTTON_SETTING: { pathKey: 'PrepaymentFunctionButtonSetting', Visiblename: 'Prepayment function button Setting', parent: 'OPTIONSETTING' },
        PREPAID_ORDER_RETENTION_OPTIONS: { pathKey: 'PrepaidOrderRetentionOptions', Visiblename: 'Prepaid order Retention options', parent: 'OPTIONSETTING' },
        DELIVERY_SETTINGS: { pathKey: 'DeliverySettings', Visiblename: 'Delivery Settings', parent: 'OPTIONSETTING' },
        DELIVERY_ORDER: { pathKey: 'DeliveryOrder', Visiblename: 'Delivery order', parent: 'OPTIONSETTING' },
        CHANGE_WEIGHT_CONTROL: { pathKey: 'ChangeWeightControl', Visiblename: 'Change weight control', parent: 'OPTIONSETTING' },
        DISCOUNT_OPTION: { pathKey: 'DiscountOption', Visiblename: 'Discount Option', parent: 'OPTIONSETTING' },
        PAYMENT_OPTIONS_IMMEDIATELY: { pathKey: 'PaymentOptionsImmediately', Visiblename: 'Payment options immediately', parent: 'OPTIONSETTING' },
        NOTICE_POPUP_OPTION: { pathKey: 'NoticePopupOption', Visiblename: 'Notice popup option', parent: 'OPTIONSETTING' },
        SET_ALL_CANCELLATION_TYPE: { pathKey: 'SetAllCancellationType', Visiblename: 'Set all cancellation type', parent: 'OPTIONSETTING' },
        CURRENCY_CHANGE_OPTION: { pathKey: 'CurrencyChangeOption', Visiblename: 'Currency Change Option', parent: 'OPTIONSETTING' },
        ENABLE_KEEP_UNIT_CHANGE: { pathKey: 'EnableKeepUnitChange', Visiblename: 'Enable Keep Unit Change', parent: 'OPTIONSETTING' },
        RECEIPT: { pathKey: 'Receipt', Visiblename: 'Receipt', parent: 'PRINTOPTIONS' },
        CUSTOMER_ORDER_PRINT: { pathKey: 'CustomerOrderPrint', Visiblename: 'Customer Order Print', parent: 'PRINTOPTIONS' },
        KITCHEN_ORDER_PRINT: { pathKey: 'KitchenOrderPrint', Visiblename: 'Kitchen Order Print', parent: 'PRINTOPTIONS' },
        WAITING_LIST_TAG: { pathKey: 'WaitingListTag', Visiblename: 'Waiting List Tag', parent: 'PRINTOPTIONS' },
        USE_SECURITY_FUNCTION_BY_TASKS: { pathKey: 'UseSecurityFunctionByTasks', Visiblename: 'Use Security Function by Tasks', parent: 'SECURITY' },
        SECURITY_GROUP: { pathKey: 'SecurityGroup', Visiblename: 'Security Group', parent: 'SECURITY' },
        EMAIL_SERVER: { pathKey: 'EmailServer', Visiblename: 'Email Server', parent: 'NETWORKSERVER' },
        ANNOUNCEMENT: { pathKey: 'Announcement', Visiblename: 'Announcement' },
        PAYROLL: { pathKey: 'Payroll', Visiblename: 'Pay roll' },
        TIME_CARD: { pathKey: 'Time Card', Visiblename: 'Time Card' },
        LIST_OF_INFORMATION_BY_FORCE: { pathKey: 'List of information by force', Visiblename: 'List of information by force' },
        CUSTOMER_GROUP: { pathKey: 'CustomerGroup', Visiblename: 'Customer Group' },
        CUSTOMER_MANAGEMENT: { pathKey: 'CustomerManagement', Visiblename: 'Customer Management' },
        MEMBERSHIP_LIST: { pathKey: 'MembershipList', Visiblename: 'Membership List' },
        CUSTOMER_SALES_TOTAL: { pathKey: 'CustomerSalesTotal', Visiblename: 'Customer Sales Total' },
        CUSTOMER_DETAILED_SALES_REPORT: { pathKey: 'CustomerDetailedSalesReport', Visiblename: 'Customer Detailed Sales Report' },
        POINT_REPORT: { pathKey: 'PointReport', Visiblename: 'Point Report' },
        MONTHLY_COMPARISON: { pathKey: 'MonthlyComparison', Visiblename: 'Monthly Comparison' },
        YEARLY_COMPARISON: { pathKey: 'YearlyComparison', Visiblename: 'Yearly Comparison' },
        TOTAL_CATEGORY_SALES_BY_STORE: { pathKey: 'TotalCategorySalesByStore', Visiblename: 'Total Category Sales By Store' },
        TOTAL_ITEM_SALES_BY_STORE: { pathKey: 'TotalItemSalesByStore', Visiblename: 'Total Item Sales By Store' },
        TOTAL_STORE_SALES_BY_CATEGORY: { pathKey: 'TotalStoreSalesByCategory', Visiblename: 'Total Store Sales By Category' },
        TOTAL_SALES_SUMMARY_BY_ITEM: { pathKey: 'TotalSalesSummaryByItem', Visiblename: 'Total Sales Summary (By Item)' },
        TOTAL_STORE_SALES_BY_ITEM: { pathKey: 'TotalStoreSalesByItem', Visiblename: 'Total Store Sales By Item' },
        TOTAL_SALES_WEEK_BY_ITEM: { pathKey: 'TotalSalesWeekByItem', Visiblename: 'Total Sales Week By Item' },
        DAILY_SALES_BY_ITEM: { pathKey: 'DailySalesByItem', Visiblename: 'Daily Sales By Item' },
        TOTAL_SALES_HOUR_BY_ITEM: { pathKey: 'TotalSalesHourByItem', Visiblename: 'Total Sales Hour By Item' },
        TOTAL_SALES_ITEM_BY_WEEK: { pathKey: 'TotalSalesItemByWeek', Visiblename: 'Total Sales Item By Week' },
        TOTAL_SALES_ITEM_BY_HOUR: { pathKey: 'TotalSalesItemByHour', Visiblename: 'Total Sales Item By Hour' },
        TOTAL_STORE_SALES_BY_SUPPLIER: { pathKey: 'TotalStoreSalesBySupplier', Visiblename: 'Total Store Sales By Supplier' },
        SALES_AMOUNT_BY_STORE: { pathKey: 'SalesAmountByStore', Visiblename: 'Sales amount by Store' },
        MONTHLY_SALES_AMOUNT_BY_STORE: { pathKey: 'MonthlySalesAmountByStore', Visiblename: 'Monthly Sales amount by Store' },
        STORE_MONTHLY_SALES_AMOUNT: { pathKey: 'StoreMonthlySalesAmount', Visiblename: 'Store Monthly Sales amount' },
        BIZ_SMS_SETTING: { pathKey: 'BizSmsSetting', Visiblename: 'BIZ SMS Setting' },
        USER_GUIDE: { pathKey: 'UserGuide', Visiblename: 'User Guide' },
        WEB_LOGIN: { pathKey: 'WebLogin', Visiblename: 'Web Login' },
        USE_SECURITY_FUNCTION_BY_TASKS2: { pathKey: 'UseSecurityFunctionByTasks2', Visiblename: 'Use Security Function by Tasks' },
        EMPLOYEE_SECURITY: { pathKey: 'EmployeeSecurity', Visiblename: 'Employee Security' },
        SECURITY_LEVEL: { pathKey: 'SecurityLevel', Visiblename: 'Security Level' },
    },
};

export default nameMap;
